/*
================================================================================
 BASE DE DATOS: mineria
 ESQUEMA: public
 SISTEMA: Sistema web full stack para la gestión logística de insumos y compras
          en operación mina
 MOTOR: PostgreSQL
 NOTA: APA 7ma edición aplica a la documentación académica. Para la base de datos
       se aplica normalización relacional hasta 3FN, con tablas separadas,
       claves primarias, claves foráneas, catálogos, restricciones, vistas,
       datos de prueba y consultas.
================================================================================

INSTRUCCIONES EN DBEAVER
1) Crear una base de datos llamada: mineria
2) Conectarse a la base de datos mineria.
3) Abrir este script SQL y ejecutarlo completo.
4) Todo se creará en el esquema public.
*/

SET search_path TO public;
SET TIME ZONE 'America/La_Paz';

-- =============================================================================
-- 1. LIMPIEZA ORDENADA DEL ESQUEMA PUBLIC
-- =============================================================================
DROP VIEW IF EXISTS v_dashboard_resumen CASCADE;
DROP VIEW IF EXISTS v_compras_por_proveedor CASCADE;
DROP VIEW IF EXISTS v_pedidos_por_estado CASCADE;
DROP VIEW IF EXISTS v_kardex CASCADE;
DROP VIEW IF EXISTS v_stock_bajo CASCADE;
DROP VIEW IF EXISTS v_stock_actual CASCADE;

DROP TABLE IF EXISTS auditorias CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS despacho_detalles CASCADE;
DROP TABLE IF EXISTS despachos CASCADE;
DROP TABLE IF EXISTS comprobantes_compra CASCADE;
DROP TABLE IF EXISTS recepcion_detalles CASCADE;
DROP TABLE IF EXISTS recepciones_compra CASCADE;
DROP TABLE IF EXISTS orden_compra_detalles CASCADE;
DROP TABLE IF EXISTS ordenes_compra CASCADE;
DROP TABLE IF EXISTS aprobaciones_pedido CASCADE;
DROP TABLE IF EXISTS pedido_detalles CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS inventarios CASCADE;
DROP TABLE IF EXISTS politicas_stock CASCADE;
DROP TABLE IF EXISTS proveedor_insumo CASCADE;
DROP TABLE IF EXISTS insumos CASCADE;
DROP TABLE IF EXISTS almacenes CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS unidades_medida CASCADE;
DROP TABLE IF EXISTS tipos_insumo CASCADE;
DROP TABLE IF EXISTS categorias_insumo CASCADE;
DROP TABLE IF EXISTS roles_permisos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS permisos CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS areas CASCADE;

DROP FUNCTION IF EXISTS fn_recepcion_actualiza_inventario();
DROP FUNCTION IF EXISTS fn_despacho_actualiza_inventario();

-- =============================================================================
-- 2. CATÁLOGOS BASE
-- =============================================================================
CREATE TABLE areas (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_permiso VARCHAR(80) NOT NULL UNIQUE,
    modulo VARCHAR(80) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles_permisos (
    id_rol INTEGER NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
    id_permiso INTEGER NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area INTEGER NOT NULL REFERENCES areas(id_area),
    id_rol INTEGER NOT NULL REFERENCES roles(id_rol),
    nombre_completo VARCHAR(150) NOT NULL,
    nombre_usuario VARCHAR(80) NOT NULL UNIQUE,
    correo VARCHAR(150) NOT NULL UNIQUE,
    cedula_identidad VARCHAR(30) UNIQUE,
    complemento_ci VARCHAR(10),
    expedido_ci VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    cargo VARCHAR(100),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    ultimo_inicio_sesion TIMESTAMPTZ,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0 CHECK (intentos_fallidos >= 0),
    cambio_obligatorio BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE categorias_insumo (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE tipos_insumo (
    id_tipo_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE unidades_medida (
    id_unidad_medida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_unidad VARCHAR(80) NOT NULL UNIQUE,
    abreviatura VARCHAR(20) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 3. MÓDULOS MAESTROS: ALMACENES, PROVEEDORES E INSUMOS
-- =============================================================================
CREATE TABLE almacenes (
    id_almacen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_almacen VARCHAR(30) NOT NULL UNIQUE,
    nombre_almacen VARCHAR(120) NOT NULL,
    tipo_almacen VARCHAR(40) NOT NULL CHECK (tipo_almacen IN (
        'SUPERFICIE', 'SUBTERRANEO', 'POLVORIN', 'SEGURIDAD_INDUSTRIAL',
        'HERRAMIENTAS_REPUESTOS', 'COMBUSTIBLE', 'LUBRICANTES', 'TEMPORAL'
    )),
    ubicacion VARCHAR(180) NOT NULL,
    id_responsable_principal INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    id_responsable_suplente INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    telefono_contacto VARCHAR(30),
    horario_atencion VARCHAR(120),
    descripcion TEXT,
    capacidad_maxima NUMERIC(14,2) CHECK (capacidad_maxima IS NULL OR capacidad_maxima >= 0),
    capacidad_minima_recomendada NUMERIC(14,2) CHECK (capacidad_minima_recomendada IS NULL OR capacidad_minima_recomendada >= 0),
    tipo_almacenamiento VARCHAR(120),
    observaciones_seguridad TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_proveedor VARCHAR(30) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    nombre_comercial VARCHAR(150),
    nit VARCHAR(30) NOT NULL UNIQUE,
    rubro VARCHAR(120) NOT NULL,
    tipo_insumos_provee TEXT,
    persona_contacto VARCHAR(120),
    cargo_contacto VARCHAR(100),
    telefono VARCHAR(30),
    celular_whatsapp VARCHAR(30),
    correo VARCHAR(150),
    direccion TEXT,
    ciudad VARCHAR(80),
    condiciones_pago VARCHAR(120),
    forma_pago VARCHAR(120),
    tiempo_estimado_entrega VARCHAR(80),
    calificacion NUMERIC(3,2) CHECK (calificacion IS NULL OR calificacion BETWEEN 0 AND 5),
    documentacion_vigente BOOLEAN DEFAULT TRUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE insumos (
    id_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL REFERENCES categorias_insumo(id_categoria),
    id_tipo_insumo INTEGER NOT NULL REFERENCES tipos_insumo(id_tipo_insumo),
    id_unidad_medida INTEGER NOT NULL REFERENCES unidades_medida(id_unidad_medida),
    id_unidad_medida_secundaria INTEGER REFERENCES unidades_medida(id_unidad_medida),
    codigo_interno VARCHAR(40) NOT NULL UNIQUE,
    codigo_barra_qr VARCHAR(80) UNIQUE,
    nombre_insumo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    presentacion VARCHAR(100),
    precio_referencial NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (precio_referencial >= 0),
    stock_minimo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    ubicacion_sugerida VARCHAR(120),
    requiere_control_especial BOOLEAN NOT NULL DEFAULT FALSE,
    es_peligroso_inflamable BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_vencimiento DATE,
    imagen_url VARCHAR(255),
    ficha_tecnica_url VARCHAR(255),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE proveedor_insumo (
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo) ON DELETE CASCADE,
    precio_referencial NUMERIC(14,2) CHECK (precio_referencial IS NULL OR precio_referencial >= 0),
    tiempo_entrega_dias INTEGER CHECK (tiempo_entrega_dias IS NULL OR tiempo_entrega_dias >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    PRIMARY KEY (id_proveedor, id_insumo)
);

-- =============================================================================
-- 4. INVENTARIO, POLÍTICAS DE STOCK Y MOVIMIENTOS
-- =============================================================================
CREATE TABLE politicas_stock (
    id_politica_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo) ON DELETE CASCADE,
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen) ON DELETE CASCADE,
    stock_minimo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    stock_maximo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_maximo >= 0),
    stock_seguridad NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_seguridad >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    UNIQUE (id_insumo, id_almacen),
    CHECK (stock_maximo = 0 OR stock_maximo >= stock_minimo)
);

CREATE TABLE inventarios (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    stock_fisico NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_fisico >= 0),
    stock_reservado NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_reservado >= 0),
    stock_disponible NUMERIC(14,2) GENERATED ALWAYS AS (stock_fisico - stock_reservado) STORED,
    costo_promedio NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (costo_promedio >= 0),
    valor_total_stock NUMERIC(14,2) GENERATED ALWAYS AS (stock_fisico * costo_promedio) STORED,
    lote VARCHAR(80),
    numero_serie VARCHAR(80),
    fecha_vencimiento DATE,
    ubicacion_interna VARCHAR(120),
    estado_stock VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado_stock IN ('DISPONIBLE', 'RESERVADO', 'AGOTADO', 'OBSERVADO')),
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    UNIQUE (id_insumo, id_almacen),
    CHECK (stock_reservado <= stock_fisico)
);

CREATE TABLE movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_movimiento VARCHAR(40) NOT NULL UNIQUE,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo_movimiento VARCHAR(40) NOT NULL CHECK (tipo_movimiento IN (
        'ENTRADA_COMPRA', 'SALIDA_DESPACHO', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO',
        'DEVOLUCION', 'TRANSFERENCIA_SALIDA', 'TRANSFERENCIA_ENTRADA', 'CORRECCION'
    )),
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen_origen INTEGER REFERENCES almacenes(id_almacen),
    id_almacen_destino INTEGER REFERENCES almacenes(id_almacen),
    cantidad NUMERIC(14,2) NOT NULL CHECK (cantidad > 0),
    costo_unitario NUMERIC(14,2) DEFAULT 0 CHECK (costo_unitario >= 0),
    motivo TEXT NOT NULL,
    documento_respaldo VARCHAR(255),
    usuario_responsable INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 5. PEDIDOS Y APROBACIONES
-- =============================================================================
CREATE TABLE pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(40) NOT NULL UNIQUE,
    id_usuario_solicitante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_area_solicitante INTEGER NOT NULL REFERENCES areas(id_area),
    fecha_pedido TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_requerida TIMESTAMPTZ NOT NULL,
    tipo_pedido VARCHAR(30) NOT NULL CHECK (tipo_pedido IN ('NORMAL', 'URGENTE', 'REPOSICION', 'EMERGENCIA', 'MANTENIMIENTO', 'OPERACION')),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    justificacion TEXT NOT NULL,
    estado_pedido VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pedido IN (
        'PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO', 'EN_COMPRA',
        'EN_DESPACHO', 'ENTREGADO_PARCIAL', 'ENTREGADO_COMPLETO', 'CANCELADO'
    )),
    estado_aprobacion VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO')),
    estado_atencion VARCHAR(40) NOT NULL DEFAULT 'SIN_ATENDER' CHECK (estado_atencion IN ('SIN_ATENDER', 'EN_PROCESO', 'ATENDIDO_PARCIAL', 'ATENDIDO_TOTAL')),
    id_proveedor_sugerido INTEGER REFERENCES proveedores(id_proveedor),
    archivo_adjunto VARCHAR(255),
    centro_costo VARCHAR(80),
    lugar_uso VARCHAR(120),
    turno_guardia VARCHAR(80),
    observaciones TEXT,
    id_usuario_revisor INTEGER REFERENCES usuarios(id_usuario),
    fecha_revision TIMESTAMPTZ,
    motivo_rechazo TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE pedido_detalles (
    id_pedido_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_aprobada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_aprobada >= 0),
    cantidad_despachada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_despachada >= 0),
    cantidad_pendiente NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_aprobada - cantidad_despachada) STORED,
    observacion TEXT,
    CHECK (cantidad_aprobada <= cantidad_solicitada),
    CHECK (cantidad_despachada <= cantidad_aprobada)
);

CREATE TABLE reservas_stock (
    id_reserva_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario INTEGER NOT NULL REFERENCES inventarios(id_inventario) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_pedido_detalle INTEGER NOT NULL REFERENCES pedido_detalles(id_pedido_detalle) ON DELETE CASCADE,
    cantidad_reservada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_reservada >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'LIBERADA')),
    fecha_reserva TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_liberacion TIMESTAMPTZ,
    UNIQUE (id_pedido_detalle, id_almacen)
);

CREATE TABLE aprobaciones_pedido (
    id_aprobacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_usuario_aprobador INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    nivel_aprobacion INTEGER NOT NULL DEFAULT 1 CHECK (nivel_aprobacion >= 1),
    fecha_aprobacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_aprobacion VARCHAR(30) NOT NULL CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO')),
    observaciones TEXT,
    motivo_rechazo TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 6. COMPRAS, RECEPCIONES Y COMPROBANTES
-- =============================================================================
CREATE TABLE ordenes_compra (
    id_orden_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden VARCHAR(40) NOT NULL UNIQUE,
    codigo_correlativo VARCHAR(40) NOT NULL UNIQUE,
    id_pedido INTEGER REFERENCES pedidos(id_pedido),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_estimada_entrega TIMESTAMPTZ,
    condicion_pago VARCHAR(120),
    forma_pago VARCHAR(120),
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pago IN ('PENDIENTE', 'PAGADO_PARCIAL', 'PAGADO_COMPLETO', 'ANULADO')),
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    descuento NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    total_final NUMERIC(14,2) GENERATED ALWAYS AS (subtotal - descuento) STORED,
    estado_compra VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_compra IN ('PENDIENTE', 'EN_PROCESO', 'RECIBIDA_PARCIAL', 'RECIBIDA_COMPLETA', 'ANULADA')),
    observaciones TEXT,
    usuario_genera INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE orden_compra_detalles (
    id_orden_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_comprada NUMERIC(14,2) NOT NULL CHECK (cantidad_comprada > 0),
    precio_unitario NUMERIC(14,2) NOT NULL CHECK (precio_unitario >= 0),
    subtotal NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_comprada * precio_unitario) STORED,
    observacion TEXT
);

CREATE TABLE recepciones_compra (
    id_recepcion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_recepcion VARCHAR(40) NOT NULL UNIQUE,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    id_almacen_destino INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    fecha_estimada_recepcion TIMESTAMPTZ,
    fecha_real_recepcion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_responsable_recepcion INTEGER REFERENCES usuarios(id_usuario),
    estado_recepcion VARCHAR(40) NOT NULL CHECK (estado_recepcion IN ('PENDIENTE', 'RECIBIDA_PARCIAL', 'RECIBIDA_COMPLETA', 'OBSERVADA', 'RECHAZADA')),
    documento_respaldo VARCHAR(255),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE recepcion_detalles (
    id_recepcion_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recepcion INTEGER NOT NULL REFERENCES recepciones_compra(id_recepcion) ON DELETE CASCADE,
    id_orden_detalle INTEGER NOT NULL REFERENCES orden_compra_detalles(id_orden_detalle),
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_comprada NUMERIC(14,2) NOT NULL CHECK (cantidad_comprada > 0),
    cantidad_recibida NUMERIC(14,2) NOT NULL CHECK (cantidad_recibida >= 0),
    cantidad_aceptada NUMERIC(14,2) NOT NULL CHECK (cantidad_aceptada >= 0),
    cantidad_rechazada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_rechazada >= 0),
    cantidad_faltante NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_faltante >= 0),
    motivo_rechazo TEXT,
    estado_conformidad VARCHAR(30) NOT NULL CHECK (estado_conformidad IN ('CONFORME', 'OBSERVADO', 'RECHAZADO')),
    observaciones TEXT,
    CHECK (cantidad_aceptada + cantidad_rechazada <= cantidad_recibida)
);

CREATE TABLE comprobantes_compra (
    id_comprobante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_comprobante VARCHAR(60) NOT NULL UNIQUE,
    tipo_comprobante VARCHAR(40) NOT NULL CHECK (tipo_comprobante IN ('FACTURA', 'RECIBO', 'NOTA_VENTA', 'COMPROBANTE_INTERNO', 'OTRO')),
    fecha_comprobante TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    nit_proveedor VARCHAR(30) NOT NULL,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra),
    monto_subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_subtotal >= 0),
    monto_descuento NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
    monto_total NUMERIC(14,2) GENERATED ALWAYS AS (monto_subtotal - monto_descuento) STORED,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    estado_comprobante VARCHAR(30) NOT NULL DEFAULT 'REGISTRADO' CHECK (estado_comprobante IN ('REGISTRADO', 'OBSERVADO', 'ANULADO')),
    archivo_comprobante VARCHAR(255),
    observaciones TEXT,
    usuario_registra INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 7. DESPACHOS
-- =============================================================================
CREATE TABLE despachos (
    id_despacho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_despacho VARCHAR(40) NOT NULL UNIQUE,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido),
    id_area_solicitante INTEGER NOT NULL REFERENCES areas(id_area),
    id_usuario_solicitante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_almacen_salida INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    id_responsable_almacen INTEGER REFERENCES usuarios(id_usuario),
    persona_recibe VARCHAR(150) NOT NULL,
    fecha_programada_entrega DATE,
    fecha_real_entrega TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo_despacho VARCHAR(30) NOT NULL CHECK (tipo_despacho IN ('NORMAL', 'URGENTE', 'PARCIAL', 'DEVOLUCION', 'REPOSICION')),
    estado_despacho VARCHAR(40) NOT NULL CHECK (estado_despacho IN ('PENDIENTE_ENTREGA', 'ENTREGADO_PARCIAL', 'ENTREGADO_COMPLETO', 'CANCELADO', 'OBSERVADO')),
    confirmacion_recepcion BOOLEAN NOT NULL DEFAULT FALSE,
    evidencia_entrega VARCHAR(255),
    observaciones TEXT,
    usuario_registra INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE despacho_detalles (
    id_despacho_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_despacho INTEGER NOT NULL REFERENCES despachos(id_despacho) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_aprobada NUMERIC(14,2) NOT NULL CHECK (cantidad_aprobada >= 0),
    cantidad_entregada NUMERIC(14,2) NOT NULL CHECK (cantidad_entregada >= 0),
    cantidad_pendiente NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_aprobada - cantidad_entregada) STORED,
    estado_conformidad VARCHAR(30) NOT NULL CHECK (estado_conformidad IN ('CONFORME', 'OBSERVADO', 'RECHAZADO')),
    observacion TEXT,
    CHECK (cantidad_entregada <= cantidad_aprobada)
);

-- =============================================================================
-- 8. NOTIFICACIONES Y AUDITORÍA
-- =============================================================================
CREATE TABLE notificaciones (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_notificacion VARCHAR(50) NOT NULL CHECK (tipo_notificacion IN (
        'STOCK_BAJO', 'INSUMO_SIN_STOCK', 'PEDIDO_CREADO', 'PEDIDO_APROBADO',
        'PEDIDO_RECHAZADO', 'PEDIDO_OBSERVADO', 'PEDIDO_EN_COMPRA', 'COMPRA_REGISTRADA',
        'COMPRA_RECIBIDA_PARCIAL', 'COMPRA_RECIBIDA_COMPLETA', 'DESPACHO_REALIZADO',
        'COMPROBANTE_REGISTRADO', 'COMPROBANTE_OBSERVADO', 'USUARIO_CREADO', 'AUDITORIA_IMPORTANTE'
    )),
    titulo VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    id_usuario_destinatario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    modulo_relacionado VARCHAR(80),
    id_registro_relacionado INTEGER,
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    estado_notificacion VARCHAR(20) NOT NULL DEFAULT 'NO_LEIDA' CHECK (estado_notificacion IN ('NO_LEIDA', 'LEIDA', 'ARCHIVADA')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_lectura TIMESTAMPTZ,
    usuario_genera INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE auditorias (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    accion_realizada VARCHAR(150) NOT NULL,
    tipo_accion VARCHAR(40) NOT NULL CHECK (tipo_accion IN (
        'CREAR', 'EDITAR', 'ELIMINAR', 'ACTIVAR', 'DESACTIVAR', 'APROBAR', 'RECHAZAR',
        'ANULAR', 'LOGIN', 'LOGOUT', 'CONSULTAR',
        'REGISTRAR_COMPRA', 'REGISTRAR_RECEPCION', 'REGISTRAR_COMPROBANTE',
        'REALIZAR_DESPACHO', 'AJUSTAR_INVENTARIO', 'INICIAR_SESION', 'CERRAR_SESION',
        'CAMBIAR_CONTRASENA', 'CAMBIAR_PERMISOS'
    )),
    modulo_afectado VARCHAR(80) NOT NULL,
    tabla_afectada VARCHAR(80),
    id_registro_afectado INTEGER,
    registro_anterior JSONB,
    registro_nuevo JSONB,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    direccion_ip VARCHAR(60),
    navegador_dispositivo VARCHAR(255),
    motivo_cambio TEXT,
    observaciones TEXT
);

-- =============================================================================
-- 9. ÍNDICES PARA MEJORAR CONSULTAS
-- =============================================================================
CREATE INDEX idx_usuarios_area ON usuarios(id_area);
CREATE INDEX idx_usuarios_rol ON usuarios(id_rol);
CREATE INDEX idx_insumos_categoria ON insumos(id_categoria);
CREATE INDEX idx_insumos_tipo ON insumos(id_tipo_insumo);
CREATE INDEX idx_inventarios_insumo ON inventarios(id_insumo);
CREATE INDEX idx_inventarios_almacen ON inventarios(id_almacen);
CREATE INDEX idx_movimientos_insumo_fecha ON movimientos_inventario(id_insumo, fecha_movimiento);
CREATE INDEX idx_pedidos_estado ON pedidos(estado_pedido);
CREATE INDEX idx_pedidos_area ON pedidos(id_area_solicitante);
CREATE INDEX idx_ordenes_proveedor ON ordenes_compra(id_proveedor);
CREATE INDEX idx_despachos_pedido ON despachos(id_pedido);
CREATE INDEX idx_notificaciones_usuario_estado ON notificaciones(id_usuario_destinatario, estado_notificacion);
CREATE INDEX idx_auditorias_usuario_fecha ON auditorias(id_usuario, fecha_hora);

-- =============================================================================
-- 10. FUNCIONES Y TRIGGERS PARA ACTUALIZACIÓN AUTOMÁTICA DE INVENTARIO
-- =============================================================================
CREATE OR REPLACE FUNCTION fn_recepcion_actualiza_inventario()
RETURNS TRIGGER AS $$
DECLARE
    v_almacen INTEGER;
    v_usuario INTEGER;
    v_costo NUMERIC(14,2);
    v_numero_recepcion VARCHAR(40);
BEGIN
    IF NEW.cantidad_aceptada > 0 THEN
        SELECT rc.id_almacen_destino, rc.id_responsable_recepcion, rc.numero_recepcion
        INTO v_almacen, v_usuario, v_numero_recepcion
        FROM recepciones_compra rc
        WHERE rc.id_recepcion = NEW.id_recepcion;

        SELECT ocd.precio_unitario
        INTO v_costo
        FROM orden_compra_detalles ocd
        WHERE ocd.id_orden_detalle = NEW.id_orden_detalle;

        INSERT INTO inventarios (
            id_insumo, id_almacen, stock_fisico, stock_reservado,
            costo_promedio, fecha_ultima_actualizacion, creado_por
        )
        VALUES (
            NEW.id_insumo, v_almacen, NEW.cantidad_aceptada, 0,
            COALESCE(v_costo, 0), NOW(), v_usuario
        )
        ON CONFLICT (id_insumo, id_almacen)
        DO UPDATE SET
            costo_promedio = CASE
                WHEN (inventarios.stock_fisico + EXCLUDED.stock_fisico) > 0 THEN
                    ROUND(((inventarios.stock_fisico * inventarios.costo_promedio) +
                           (EXCLUDED.stock_fisico * EXCLUDED.costo_promedio)) /
                          (inventarios.stock_fisico + EXCLUDED.stock_fisico), 2)
                ELSE EXCLUDED.costo_promedio
            END,
            stock_fisico = inventarios.stock_fisico + EXCLUDED.stock_fisico,
            estado_stock = 'DISPONIBLE',
            fecha_ultima_actualizacion = NOW(),
            actualizado_por = v_usuario;

        INSERT INTO movimientos_inventario (
            numero_movimiento, tipo_movimiento, id_insumo, id_almacen_destino,
            cantidad, costo_unitario, motivo, documento_respaldo, usuario_responsable, observaciones
        )
        VALUES (
            'MOV-REC-' || NEW.id_recepcion_detalle,
            'ENTRADA_COMPRA',
            NEW.id_insumo,
            v_almacen,
            NEW.cantidad_aceptada,
            COALESCE(v_costo, 0),
            'Entrada automática por recepción de compra',
            v_numero_recepcion,
            v_usuario,
            'Movimiento generado automáticamente desde recepción de compra.'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_recepcion_actualiza_inventario
AFTER INSERT ON recepcion_detalles
FOR EACH ROW
EXECUTE FUNCTION fn_recepcion_actualiza_inventario();

CREATE OR REPLACE FUNCTION fn_despacho_actualiza_inventario()
RETURNS TRIGGER AS $$
DECLARE
    v_almacen INTEGER;
    v_usuario INTEGER;
    v_id_pedido INTEGER;
    v_numero_despacho VARCHAR(40);
    v_stock_fisico NUMERIC(14,2);
    v_stock_reservado NUMERIC(14,2);
    v_reservado_pedido NUMERIC(14,2);
    v_costo NUMERIC(14,2);
BEGIN
    IF NEW.cantidad_entregada > 0 THEN
        SELECT d.id_almacen_salida, d.id_responsable_almacen, d.id_pedido, d.numero_despacho
        INTO v_almacen, v_usuario, v_id_pedido, v_numero_despacho
        FROM despachos d
        WHERE d.id_despacho = NEW.id_despacho;

        SELECT i.stock_fisico, i.stock_reservado, i.costo_promedio
        INTO v_stock_fisico, v_stock_reservado, v_costo
        FROM inventarios i
        WHERE i.id_insumo = NEW.id_insumo
          AND i.id_almacen = v_almacen
        FOR UPDATE;

        SELECT COALESCE(SUM(rs.cantidad_reservada), 0)
        INTO v_reservado_pedido
        FROM reservas_stock rs
        WHERE rs.id_pedido = v_id_pedido
          AND rs.id_insumo = NEW.id_insumo
          AND rs.id_almacen = v_almacen
          AND rs.estado = 'ACTIVA';

        IF COALESCE(v_stock_fisico, 0) < NEW.cantidad_entregada
           OR (
             v_reservado_pedido < NEW.cantidad_entregada
             AND COALESCE(v_stock_fisico, 0) - COALESCE(v_stock_reservado, 0) < NEW.cantidad_entregada
           ) THEN
            RAISE EXCEPTION 'Stock insuficiente para el insumo %. Stock fisico: %, reservado para pedido: %, cantidad solicitada: %',
                NEW.id_insumo, COALESCE(v_stock_fisico, 0), COALESCE(v_reservado_pedido, 0), NEW.cantidad_entregada;
        END IF;

        UPDATE inventarios
        SET stock_fisico = stock_fisico - NEW.cantidad_entregada,
            estado_stock = CASE
                WHEN stock_fisico - NEW.cantidad_entregada = 0 THEN 'AGOTADO'
                WHEN stock_reservado > 0 THEN 'RESERVADO'
                ELSE 'DISPONIBLE'
            END,
            fecha_ultima_actualizacion = NOW(),
            actualizado_por = v_usuario
        WHERE id_insumo = NEW.id_insumo
          AND id_almacen = v_almacen;

        INSERT INTO movimientos_inventario (
            numero_movimiento, tipo_movimiento, id_insumo, id_almacen_origen,
            cantidad, costo_unitario, motivo, documento_respaldo, usuario_responsable, observaciones
        )
        VALUES (
            'MOV-DES-' || NEW.id_despacho_detalle,
            'SALIDA_DESPACHO',
            NEW.id_insumo,
            v_almacen,
            NEW.cantidad_entregada,
            COALESCE(v_costo, 0),
            'Salida automática por despacho de insumos',
            v_numero_despacho,
            v_usuario,
            'Movimiento generado automáticamente desde despacho.'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_despacho_actualiza_inventario
AFTER INSERT ON despacho_detalles
FOR EACH ROW
EXECUTE FUNCTION fn_despacho_actualiza_inventario();

-- =============================================================================
-- 11. VISTAS DE REPORTES Y DASHBOARD
-- =============================================================================
CREATE VIEW v_stock_actual AS
SELECT
    i.id_inventario,
    ins.codigo_interno,
    ins.nombre_insumo,
    c.nombre_categoria,
    ti.nombre_tipo,
    um.abreviatura AS unidad_medida,
    a.codigo_almacen,
    a.nombre_almacen,
    a.tipo_almacen,
    i.stock_fisico,
    i.stock_reservado,
    i.stock_disponible,
    ins.stock_minimo,
    COALESCE(ps.stock_maximo, 0) AS stock_maximo,
    COALESCE(ps.stock_seguridad, 0) AS stock_seguridad,
    i.costo_promedio,
    i.valor_total_stock,
    i.estado_stock,
    i.fecha_ultima_actualizacion
FROM inventarios i
INNER JOIN insumos ins ON ins.id_insumo = i.id_insumo
INNER JOIN categorias_insumo c ON c.id_categoria = ins.id_categoria
INNER JOIN tipos_insumo ti ON ti.id_tipo_insumo = ins.id_tipo_insumo
INNER JOIN unidades_medida um ON um.id_unidad_medida = ins.id_unidad_medida
INNER JOIN almacenes a ON a.id_almacen = i.id_almacen
LEFT JOIN politicas_stock ps ON ps.id_insumo = i.id_insumo AND ps.id_almacen = i.id_almacen;

CREATE VIEW v_stock_bajo AS
SELECT *
FROM v_stock_actual
WHERE stock_disponible <= stock_minimo;

CREATE VIEW v_kardex AS
SELECT
    mi.fecha_movimiento,
    mi.numero_movimiento,
    ins.codigo_interno,
    ins.nombre_insumo,
    mi.tipo_movimiento,
    CASE WHEN mi.tipo_movimiento IN ('ENTRADA_COMPRA', 'AJUSTE_POSITIVO', 'DEVOLUCION', 'TRANSFERENCIA_ENTRADA') THEN mi.cantidad ELSE 0 END AS entrada,
    CASE WHEN mi.tipo_movimiento IN ('SALIDA_DESPACHO', 'AJUSTE_NEGATIVO', 'TRANSFERENCIA_SALIDA') THEN mi.cantidad ELSE 0 END AS salida,
    mi.costo_unitario,
    mi.motivo,
    COALESCE(ao.nombre_almacen, '-') AS almacen_origen,
    COALESCE(ad.nombre_almacen, '-') AS almacen_destino,
    u.nombre_completo AS usuario_responsable,
    mi.documento_respaldo,
    mi.observaciones
FROM movimientos_inventario mi
INNER JOIN insumos ins ON ins.id_insumo = mi.id_insumo
LEFT JOIN almacenes ao ON ao.id_almacen = mi.id_almacen_origen
LEFT JOIN almacenes ad ON ad.id_almacen = mi.id_almacen_destino
LEFT JOIN usuarios u ON u.id_usuario = mi.usuario_responsable;

CREATE VIEW v_pedidos_por_estado AS
SELECT
    estado_pedido,
    COUNT(*) AS total_pedidos
FROM pedidos
GROUP BY estado_pedido;

CREATE VIEW v_compras_por_proveedor AS
SELECT
    p.codigo_proveedor,
    p.razon_social,
    COUNT(oc.id_orden_compra) AS total_compras,
    COALESCE(SUM(oc.total_final), 0) AS monto_total_comprado
FROM proveedores p
LEFT JOIN ordenes_compra oc ON oc.id_proveedor = p.id_proveedor
GROUP BY p.codigo_proveedor, p.razon_social;

CREATE VIEW v_dashboard_resumen AS
SELECT
    (SELECT COUNT(*) FROM insumos WHERE estado = 'ACTIVO') AS total_insumos_activos,
    (SELECT COUNT(*) FROM proveedores WHERE estado = 'ACTIVO') AS total_proveedores_activos,
    (SELECT COUNT(*) FROM almacenes WHERE estado = 'ACTIVO') AS total_almacenes_activos,
    (SELECT COUNT(*) FROM usuarios WHERE estado = 'ACTIVO') AS total_usuarios_activos,
    (SELECT COUNT(*) FROM pedidos WHERE estado_pedido = 'PENDIENTE') AS pedidos_pendientes,
    (SELECT COUNT(*) FROM pedidos WHERE estado_pedido = 'APROBADO') AS pedidos_aprobados,
    (SELECT COUNT(*) FROM ordenes_compra WHERE estado_compra IN ('PENDIENTE', 'EN_PROCESO')) AS compras_en_proceso,
    (SELECT COUNT(*) FROM ordenes_compra WHERE estado_compra = 'RECIBIDA_COMPLETA') AS compras_recibidas,
    (SELECT COUNT(*) FROM v_stock_bajo) AS insumos_con_stock_bajo,
    (SELECT COALESCE(SUM(valor_total_stock), 0) FROM inventarios) AS valor_total_inventario;

-- =============================================================================
-- 12. DATOS DE PRUEBA COMPLETOS
-- =============================================================================
-- Áreas
INSERT INTO areas (nombre_area, descripcion) VALUES
('Mina', 'Área responsable de la operación minera.'),
('Mantenimiento', 'Área encargada del mantenimiento de equipos e infraestructura.'),
('Seguridad Industrial', 'Área responsable de la seguridad industrial y dotación de EPP.'),
('Compras', 'Área encargada de gestionar compras y proveedores.'),
('Almacén', 'Área responsable del control físico de insumos.'),
('Administración', 'Área administrativa de apoyo.'),
('Transporte', 'Área de apoyo logístico y transporte.'),
('Perforación', 'Área encargada de trabajos de perforación.'),
('Operaciones', 'Área de coordinación operativa.'),
('Gerencia', 'Área de dirección y toma de decisiones.');

-- Roles
INSERT INTO roles (nombre_rol, descripcion) VALUES
('Administrador', 'Acceso total al sistema.'),
('Jefe de almacén', 'Responsable de supervisar almacenes, inventario y despachos.'),
('Encargado de almacén', 'Responsable operativo de entradas, salidas y kardex.'),
('Supervisor de mina', 'Responsable de revisar y aprobar solicitudes operativas.'),
('Encargado de compras', 'Responsable de órdenes de compra, proveedores y comprobantes.'),
('Auditor', 'Usuario con permisos de revisión, reportes y auditoría.'),
('Usuario solicitante', 'Usuario que crea pedidos de insumos según su área.');

-- Permisos
INSERT INTO permisos (codigo_permiso, modulo, descripcion) VALUES
('DASHBOARD_VER', 'Dashboard', 'Ver indicadores del dashboard.'),
('ALMACENES_GESTIONAR', 'Almacenes', 'Crear, editar y consultar almacenes.'),
('PROVEEDORES_GESTIONAR', 'Proveedores', 'Crear, editar y consultar proveedores.'),
('INSUMOS_GESTIONAR', 'Insumos', 'Crear, editar y consultar insumos.'),
('INVENTARIO_VER', 'Inventario', 'Consultar stock actual.'),
('INVENTARIO_MOVIMIENTOS', 'Inventario', 'Registrar movimientos de inventario.'),
('INVENTARIO_AJUSTES', 'Inventario', 'Registrar ajustes de inventario.'),
('PEDIDOS_CREAR', 'Pedidos', 'Crear pedidos de insumos.'),
('PEDIDOS_REVISAR', 'Pedidos', 'Revisar pedidos.'),
('PEDIDOS_APROBAR', 'Pedidos', 'Aprobar o rechazar pedidos.'),
('COMPRAS_GESTIONAR', 'Compras', 'Gestionar órdenes de compra.'),
('RECEPCIONES_REGISTRAR', 'Compras', 'Registrar recepción de compras.'),
('COMPROBANTES_REGISTRAR', 'Compras', 'Registrar comprobantes de compra.'),
('DESPACHOS_REALIZAR', 'Inventario', 'Realizar despachos de insumos.'),
('REPORTES_VER', 'Reportes', 'Ver reportes.'),
('REPORTES_EXPORTAR', 'Reportes', 'Exportar reportes a PDF o Excel.'),
('AUDITORIA_VER', 'Auditoría', 'Consultar auditoría del sistema.'),
('USUARIOS_GESTIONAR', 'Usuarios', 'Gestionar usuarios.'),
('ROLES_GESTIONAR', 'Usuarios', 'Gestionar roles y permisos.'),
('NOTIFICACIONES_VER', 'Notificaciones', 'Ver notificaciones internas.');

-- Permisos por rol
INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r CROSS JOIN permisos p
WHERE r.nombre_rol = 'Administrador';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'ALMACENES_GESTIONAR', 'INVENTARIO_VER', 'INVENTARIO_MOVIMIENTOS',
    'INVENTARIO_AJUSTES', 'DESPACHOS_REALIZAR', 'REPORTES_VER', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Jefe de almacén';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'INVENTARIO_VER', 'INVENTARIO_MOVIMIENTOS', 'DESPACHOS_REALIZAR', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Encargado de almacén';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'PEDIDOS_REVISAR', 'PEDIDOS_APROBAR', 'REPORTES_VER', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Supervisor de mina';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'PROVEEDORES_GESTIONAR', 'COMPRAS_GESTIONAR',
    'RECEPCIONES_REGISTRAR', 'COMPROBANTES_REGISTRAR', 'REPORTES_VER', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Encargado de compras';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'REPORTES_VER', 'AUDITORIA_VER', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Auditor';

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r JOIN permisos p ON p.codigo_permiso IN (
    'DASHBOARD_VER', 'PEDIDOS_CREAR', 'NOTIFICACIONES_VER'
)
WHERE r.nombre_rol = 'Usuario solicitante';

-- Usuarios. La contraseña está guardada como hash de ejemplo, no como texto plano.
INSERT INTO usuarios (id_area, id_rol, nombre_completo, nombre_usuario, correo, cedula_identidad, password_hash, telefono, cargo) VALUES
((SELECT id_area FROM areas WHERE nombre_area='Administración'), (SELECT id_rol FROM roles WHERE nombre_rol='Administrador'), 'Juan Pérez Administrador', 'jperez', 'jperez@mineria.local', '1000001 LP', '$2b$10$8ZJN77JSkRYGkB9jMeq.1OSGAnvHst9NZ0oOv8xa4GO403cZm.Ffq', '70000001', 'Administrador del sistema'),
((SELECT id_area FROM areas WHERE nombre_area='Almacén'), (SELECT id_rol FROM roles WHERE nombre_rol='Jefe de almacén'), 'María Condori Alarcón', 'mcondori', 'mcondori@mineria.local', '1000002 LP', '$2b$10$8ZJN77JSkRYGkB9jMeq.1OSGAnvHst9NZ0oOv8xa4GO403cZm.Ffq', '70000002', 'Jefe de almacén'),
((SELECT id_area FROM areas WHERE nombre_area='Mina'), (SELECT id_rol FROM roles WHERE nombre_rol='Supervisor de mina'), 'Carlos Quispe Mamani', 'cquispe', 'cquispe@mineria.local', '1000003 LP', '$2b$10$8ZJN77JSkRYGkB9jMeq.1OSGAnvHst9NZ0oOv8xa4GO403cZm.Ffq', '70000003', 'Supervisor de mina'),
((SELECT id_area FROM areas WHERE nombre_area='Compras'), (SELECT id_rol FROM roles WHERE nombre_rol='Encargado de compras'), 'Ana Vargas Choque', 'avargas', 'avargas@mineria.local', '1000004 LP', '$2b$10$8ZJN77JSkRYGkB9jMeq.1OSGAnvHst9NZ0oOv8xa4GO403cZm.Ffq', '70000004', 'Encargada de compras'),
((SELECT id_area FROM areas WHERE nombre_area='Mantenimiento'), (SELECT id_rol FROM roles WHERE nombre_rol='Usuario solicitante'), 'Luis Mamani Flores', 'lmamani', 'lmamani@mineria.local', '1000005 LP', '$2b$10$8ZJN77JSkRYGkB9jMeq.1OSGAnvHst9NZ0oOv8xa4GO403cZm.Ffq', '70000005', 'Técnico de mantenimiento');

-- Catálogos de insumos
INSERT INTO categorias_insumo (nombre_categoria, descripcion, creado_por) VALUES
('Herramientas y repuestos', 'Herramientas, piezas y repuestos de apoyo a la operación mina.', 1),
('Seguridad industrial', 'Elementos de protección personal y seguridad ocupacional.', 1),
('Lubricantes', 'Aceites, grasas y lubricantes para mantenimiento.', 1),
('Combustible', 'Combustible utilizado en equipos y operación.', 1),
('Material de perforación', 'Materiales e insumos utilizados en perforación.', 1),
('Material explosivo controlado', 'Material controlado que requiere registro y almacenamiento especial.', 1);

INSERT INTO tipos_insumo (nombre_tipo, descripcion, creado_por) VALUES
('Consumible', 'Insumo que se consume durante la operación.', 1),
('Herramienta', 'Herramienta de uso operativo.', 1),
('Repuesto', 'Repuesto de equipos o maquinaria.', 1),
('Material de seguridad', 'Insumo relacionado con seguridad industrial.', 1),
('Combustible', 'Insumo combustible.', 1),
('Material controlado', 'Insumo que requiere control especial.', 1);

INSERT INTO unidades_medida (nombre_unidad, abreviatura, descripcion) VALUES
('Unidad', 'unid', 'Unidad individual.'),
('Par', 'par', 'Par de elementos.'),
('Litro', 'L', 'Medida de volumen en litros.'),
('Kilogramo', 'kg', 'Medida de peso en kilogramos.'),
('Caja', 'caja', 'Presentación por caja.'),
('Metro', 'm', 'Medida de longitud en metros.');

-- Almacenes
INSERT INTO almacenes (
    codigo_almacen, nombre_almacen, tipo_almacen, ubicacion, id_responsable_principal,
    telefono_contacto, horario_atencion, descripcion, capacidad_maxima, capacidad_minima_recomendada,
    tipo_almacenamiento, observaciones_seguridad, creado_por
) VALUES
('ALM-SUP-001', 'Almacén de superficie', 'SUPERFICIE', 'Zona administrativa de superficie', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), '70000002', 'Lunes a sábado 08:00 - 18:00', 'Almacén principal de insumos generales.', 10000, 1000, 'Almacenamiento general', 'Ingreso restringido a personal autorizado.', 1),
('ALM-POL-001', 'Polvorín principal', 'POLVORIN', 'Zona segura y aislada de operación', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), '70000002', 'Bajo autorización', 'Almacén para material controlado.', 500, 50, 'Almacenamiento especial controlado', 'Requiere control, autorización y trazabilidad estricta.', 1),
('ALM-COM-001', 'Almacén de combustible', 'COMBUSTIBLE', 'Patio de abastecimiento', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), '70000002', 'Lunes a sábado 07:00 - 17:00', 'Almacén para combustible de operación.', 5000, 500, 'Tanques y contenedores certificados', 'Mantener señalización y control de inflamables.', 1);

-- Proveedores
INSERT INTO proveedores (
    codigo_proveedor, razon_social, nombre_comercial, nit, rubro, tipo_insumos_provee,
    persona_contacto, cargo_contacto, telefono, celular_whatsapp, correo, direccion, ciudad,
    condiciones_pago, forma_pago, tiempo_estimado_entrega, calificacion, documentacion_vigente,
    observaciones, creado_por
) VALUES
('PROV-001', 'Suministros Andinos S.R.L.', 'Suministros Andinos', '1001001001', 'Herramientas, repuestos y seguridad industrial', 'Herramientas, EPP, repuestos y material de perforación', 'Roberto Salazar', 'Ejecutivo comercial', '25250001', '72000001', 'ventas@suministrosandinos.local', 'Av. Industrial Nro. 120', 'Oruro', 'Crédito a 30 días', 'Transferencia bancaria', '3 a 5 días hábiles', 4.80, TRUE, 'Proveedor principal de herramientas y seguridad.', 1),
('PROV-002', 'Lubricantes y Combustibles Oruro S.A.', 'LubriOruro', '1001001002', 'Lubricantes y combustible', 'Aceites, lubricantes y combustible', 'Patricia Rojas', 'Responsable de ventas', '25250002', '72000002', 'contacto@lubrioruro.local', 'Zona industrial norte', 'Oruro', 'Contado o crédito a 15 días', 'Transferencia bancaria', '2 a 4 días hábiles', 4.60, TRUE, 'Proveedor de lubricantes y combustible.', 1),
('PROV-003', 'Materiales Controlados Mina S.R.L.', 'MCM Controlados', '1001001003', 'Material controlado', 'Material explosivo controlado y accesorios autorizados', 'Eduardo Lima', 'Encargado de operaciones', '25250003', '72000003', 'operaciones@mcmcontrolados.local', 'Zona autorizada de almacenamiento', 'Oruro', 'Según contrato y autorización', 'Transferencia bancaria', 'Según autorización y programación', 4.50, TRUE, 'Proveedor sujeto a control documental.', 1);

-- Insumos
INSERT INTO insumos (
    id_categoria, id_tipo_insumo, id_unidad_medida, codigo_interno, codigo_barra_qr,
    nombre_insumo, descripcion, marca, modelo, presentacion, precio_referencial,
    ubicacion_sugerida, requiere_control_especial, es_peligroso_inflamable, estado, observaciones, creado_por
) VALUES
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Seguridad industrial'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Material de seguridad'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='unid'), 'SEG-CAS-001', 'QR-SEG-CAS-001', 'Casco de seguridad minero', 'Casco de seguridad para personal de operación mina.', 'Genérico', 'Minero estándar', 'Unidad', 85.00, 'Estante EPP-01', FALSE, FALSE, 'ACTIVO', 'Uso obligatorio en operación.', 1),
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Seguridad industrial'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Material de seguridad'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='par'), 'SEG-GUA-001', 'QR-SEG-GUA-001', 'Guantes de cuero reforzado', 'Guantes de protección para trabajos operativos.', 'Genérico', 'Reforzado', 'Par', 25.00, 'Estante EPP-02', FALSE, FALSE, 'ACTIVO', 'Uso en mantenimiento y operación.', 1),
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Lubricantes'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Consumible'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='L'), 'LUB-ACE-001', 'QR-LUB-ACE-001', 'Aceite lubricante 15W40', 'Aceite lubricante para equipos de operación y mantenimiento.', 'Genérico', '15W40', 'Bidón / litro', 38.00, 'Zona lubricantes', FALSE, TRUE, 'ACTIVO', 'Mantener en zona ventilada.', 1),
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Material de perforación'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Repuesto'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='unid'), 'PER-BRO-038', 'QR-PER-BRO-038', 'Broca de perforación 38 mm', 'Broca utilizada para trabajos de perforación.', 'Genérico', '38 mm', 'Unidad', 145.00, 'Estante PER-01', FALSE, FALSE, 'ACTIVO', 'Controlar desgaste y reposición.', 1),
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Combustible'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Combustible'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='L'), 'COM-DIE-001', 'QR-COM-DIE-001', 'Diésel para operación mina', 'Combustible utilizado en equipos de operación.', 'Genérico', 'Diésel', 'Litro', 6.80, 'Tanque COM-01', TRUE, TRUE, 'ACTIVO', 'Producto inflamable con control especial.', 1),
((SELECT id_categoria FROM categorias_insumo WHERE nombre_categoria='Material explosivo controlado'), (SELECT id_tipo_insumo FROM tipos_insumo WHERE nombre_tipo='Material controlado'), (SELECT id_unidad_medida FROM unidades_medida WHERE abreviatura='caja'), 'MEC-CTRL-001', 'QR-MEC-CTRL-001', 'Material explosivo controlado tipo E', 'Material controlado para operación mina sujeto a autorización.', 'Controlado', 'Tipo E', 'Caja', 520.00, 'Polvorín principal', TRUE, TRUE, 'ACTIVO', 'Requiere autorización, registro y trazabilidad estricta.', 1);

-- Relación proveedor-insumo
INSERT INTO proveedor_insumo (id_proveedor, id_insumo, precio_referencial, tiempo_entrega_dias) VALUES
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), 85.00, 3),
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), 25.00, 3),
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), 145.00, 5),
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), 38.00, 2),
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='COM-DIE-001'), 6.80, 2),
((SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-003'), (SELECT id_insumo FROM insumos WHERE codigo_interno='MEC-CTRL-001'), 520.00, 7);

-- Políticas de stock por almacén
INSERT INTO politicas_stock (id_insumo, id_almacen, stock_minimo, stock_maximo, stock_seguridad, creado_por) VALUES
((SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 10, 100, 15, 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 20, 200, 30, 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 30, 300, 50, 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 5, 80, 10, 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='COM-DIE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-COM-001'), 300, 3000, 500, 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='MEC-CTRL-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-POL-001'), 5, 80, 10, 1);

-- Inventario inicial
INSERT INTO inventarios (id_insumo, id_almacen, stock_fisico, stock_reservado, costo_promedio, lote, ubicacion_interna, creado_por) VALUES
((SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 30, 0, 80.00, 'INI-2026-01', 'EPP-01', 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 50, 0, 22.00, 'INI-2026-01', 'EPP-02', 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 80, 0, 36.00, 'INI-2026-01', 'LUB-01', 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 5, 0, 140.00, 'INI-2026-01', 'PER-01', 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='COM-DIE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-COM-001'), 500, 0, 6.50, 'INI-2026-01', 'TANQUE-01', 1),
((SELECT id_insumo FROM insumos WHERE codigo_interno='MEC-CTRL-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-POL-001'), 10, 0, 500.00, 'INI-2026-01', 'POL-01', 1);

-- Movimientos iniciales de kardex
INSERT INTO movimientos_inventario (numero_movimiento, tipo_movimiento, id_insumo, id_almacen_destino, cantidad, costo_unitario, motivo, usuario_responsable, observaciones) VALUES
('MOV-INI-001', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 30, 80.00, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.'),
('MOV-INI-002', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 50, 22.00, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.'),
('MOV-INI-003', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 80, 36.00, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.'),
('MOV-INI-004', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), 5, 140.00, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.'),
('MOV-INI-005', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='COM-DIE-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-COM-001'), 500, 6.50, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.'),
('MOV-INI-006', 'AJUSTE_POSITIVO', (SELECT id_insumo FROM insumos WHERE codigo_interno='MEC-CTRL-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-POL-001'), 10, 500.00, 'Carga inicial de inventario', 1, 'Dato inicial de prueba.');

-- Tres pedidos completos
INSERT INTO pedidos (
    numero_pedido, id_usuario_solicitante, id_area_solicitante, fecha_pedido, fecha_requerida,
    tipo_pedido, prioridad, justificacion, estado_pedido, estado_aprobacion, estado_atencion,
    centro_costo, turno_guardia, observaciones, id_usuario_revisor, fecha_revision, creado_por, actualizado_por
) VALUES
('PED-2026-0001', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), (SELECT id_area FROM areas WHERE nombre_area='Mina'), '2026-07-04', '2026-07-06', 'OPERACION', 'ALTA', 'Reposición de EPP para personal de operación mina.', 'APROBADO', 'APROBADO', 'EN_PROCESO', 'CC-MINA-001', 'Guardia día', 'Pedido aprobado para despacho y reposición de guantes.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), NOW(), 3, 3),
('PED-2026-0002', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), (SELECT id_area FROM areas WHERE nombre_area='Perforación'), '2026-07-04', '2026-07-07', 'OPERACION', 'URGENTE', 'Brocas requeridas para trabajos de perforación programados.', 'APROBADO', 'APROBADO', 'EN_PROCESO', 'CC-PER-001', 'Guardia noche', 'Pedido requiere compra por stock insuficiente.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), NOW(), 3, 3),
('PED-2026-0003', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='lmamani'), (SELECT id_area FROM areas WHERE nombre_area='Mantenimiento'), '2026-07-04', '2026-07-08', 'MANTENIMIENTO', 'MEDIA', 'Aceite requerido para mantenimiento preventivo de equipos.', 'APROBADO', 'APROBADO', 'EN_PROCESO', 'CC-MANT-001', 'Guardia día', 'Pedido requiere compra de reposición.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), NOW(), 5, 3);

INSERT INTO pedido_detalles (id_pedido, id_insumo, cantidad_solicitada, cantidad_aprobada, cantidad_despachada, observacion) VALUES
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), 20, 20, 20, 'Cascos para personal operativo.'),
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), 60, 60, 60, 'Guantes para operación mina.'),
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), 15, 15, 15, 'Brocas para perforación.'),
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0003'), (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), 100, 100, 100, 'Aceite para mantenimiento preventivo.');

INSERT INTO aprobaciones_pedido (id_pedido, id_usuario_aprobador, nivel_aprobacion, estado_aprobacion, observaciones) VALUES
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), 1, 'APROBADO', 'Aprobado por necesidad operativa.'),
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0002'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), 1, 'APROBADO', 'Aprobado por trabajo programado de perforación.'),
((SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0003'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), 1, 'APROBADO', 'Aprobado para mantenimiento preventivo.');

-- Tres órdenes de compra relacionadas con los pedidos
INSERT INTO ordenes_compra (
    numero_orden, codigo_correlativo, id_pedido, id_proveedor, fecha_emision, fecha_estimada_entrega,
    condicion_pago, forma_pago, moneda, estado_pago, subtotal, descuento, estado_compra,
    observaciones, usuario_genera
) VALUES
('OC-2026-0001', 'OC-0001-2026', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), '2026-07-04', '2026-07-05', 'Crédito a 30 días', 'Transferencia bancaria', 'BOB', 'PENDIENTE', 660.00, 0.00, 'RECIBIDA_COMPLETA', 'Compra de reposición para completar despacho de guantes.', 4),
('OC-2026-0002', 'OC-0002-2026', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0002'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), '2026-07-04', '2026-07-06', 'Crédito a 30 días', 'Transferencia bancaria', 'BOB', 'PENDIENTE', 2900.00, 0.00, 'RECIBIDA_COMPLETA', 'Compra de brocas para perforación.', 4),
('OC-2026-0003', 'OC-0003-2026', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0003'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-002'), '2026-07-04', '2026-07-06', 'Contado', 'Transferencia bancaria', 'BOB', 'PAGADO_COMPLETO', 1900.00, 0.00, 'RECIBIDA_COMPLETA', 'Compra de aceite para mantenimiento.', 4);

INSERT INTO orden_compra_detalles (id_orden_compra, id_insumo, cantidad_solicitada, cantidad_comprada, precio_unitario, observacion) VALUES
((SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), 30, 30, 22.00, 'Reposición de guantes.'),
((SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), 20, 20, 145.00, 'Compra de brocas.'),
((SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0003'), (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), 50, 50, 38.00, 'Compra de aceite lubricante.');

-- Recepciones. Los detalles disparan triggers que actualizan inventario y kardex.
INSERT INTO recepciones_compra (
    numero_recepcion, id_orden_compra, id_proveedor, id_almacen_destino,
    fecha_estimada_recepcion, fecha_real_recepcion, id_responsable_recepcion,
    estado_recepcion, documento_respaldo, observaciones
) VALUES
('REC-2026-0001', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0001'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), '2026-07-05', '2026-07-05', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'RECIBIDA_COMPLETA', 'recepcion_guantes_0001.pdf', 'Recepción conforme.'),
('REC-2026-0002', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0002'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), '2026-07-06', '2026-07-06', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'RECIBIDA_COMPLETA', 'recepcion_brocas_0002.pdf', 'Recepción conforme.'),
('REC-2026-0003', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0003'), (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-002'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), '2026-07-06', '2026-07-06', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'RECIBIDA_COMPLETA', 'recepcion_aceite_0003.pdf', 'Recepción conforme.');

INSERT INTO recepcion_detalles (
    id_recepcion, id_orden_detalle, id_insumo, cantidad_comprada, cantidad_recibida,
    cantidad_aceptada, cantidad_rechazada, cantidad_faltante, estado_conformidad, observaciones
) VALUES
((SELECT id_recepcion FROM recepciones_compra WHERE numero_recepcion='REC-2026-0001'), (SELECT id_orden_detalle FROM orden_compra_detalles od INNER JOIN ordenes_compra oc ON oc.id_orden_compra=od.id_orden_compra WHERE oc.numero_orden='OC-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), 30, 30, 30, 0, 0, 'CONFORME', 'Cantidad recibida conforme.'),
((SELECT id_recepcion FROM recepciones_compra WHERE numero_recepcion='REC-2026-0002'), (SELECT id_orden_detalle FROM orden_compra_detalles od INNER JOIN ordenes_compra oc ON oc.id_orden_compra=od.id_orden_compra WHERE oc.numero_orden='OC-2026-0002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), 20, 20, 20, 0, 0, 'CONFORME', 'Cantidad recibida conforme.'),
((SELECT id_recepcion FROM recepciones_compra WHERE numero_recepcion='REC-2026-0003'), (SELECT id_orden_detalle FROM orden_compra_detalles od INNER JOIN ordenes_compra oc ON oc.id_orden_compra=od.id_orden_compra WHERE oc.numero_orden='OC-2026-0003'), (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), 50, 50, 50, 0, 0, 'CONFORME', 'Cantidad recibida conforme.');

-- Comprobantes
INSERT INTO comprobantes_compra (
    numero_comprobante, tipo_comprobante, fecha_comprobante, id_proveedor, nit_proveedor,
    id_orden_compra, monto_subtotal, monto_descuento, moneda,
    estado_comprobante, archivo_comprobante, observaciones, usuario_registra
) VALUES
('FAC-000001', 'FACTURA', '2026-07-05', (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), '1001001001', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0001'), 660.00, 0.00, 'BOB', 'REGISTRADO', 'factura_000001.pdf', 'Factura registrada correctamente.', 4),
('FAC-000002', 'FACTURA', '2026-07-06', (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-001'), '1001001001', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0002'), 2900.00, 0.00, 'BOB', 'REGISTRADO', 'factura_000002.pdf', 'Factura registrada correctamente.', 4),
('FAC-000003', 'FACTURA', '2026-07-06', (SELECT id_proveedor FROM proveedores WHERE codigo_proveedor='PROV-002'), '1001001002', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0003'), 1900.00, 0.00, 'BOB', 'REGISTRADO', 'factura_000003.pdf', 'Factura registrada correctamente.', 4);

-- Tres despachos. Los detalles disparan triggers que descuentan inventario y registran kardex.
INSERT INTO despachos (
    numero_despacho, id_pedido, id_area_solicitante, id_usuario_solicitante, id_almacen_salida,
    id_responsable_almacen, persona_recibe, fecha_programada_entrega, fecha_real_entrega,
    tipo_despacho, estado_despacho, confirmacion_recepcion, evidencia_entrega, observaciones, usuario_registra
) VALUES
('DES-2026-0001', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), (SELECT id_area FROM areas WHERE nombre_area='Mina'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'Carlos Quispe Mamani', '2026-07-06', '2026-07-06', 'NORMAL', 'ENTREGADO_COMPLETO', TRUE, 'evidencia_des_0001.pdf', 'Despacho completo de EPP.', 2),
('DES-2026-0002', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0002'), (SELECT id_area FROM areas WHERE nombre_area='Perforación'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'Carlos Quispe Mamani', '2026-07-07', '2026-07-07', 'URGENTE', 'ENTREGADO_COMPLETO', TRUE, 'evidencia_des_0002.pdf', 'Despacho completo de brocas.', 2),
('DES-2026-0003', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0003'), (SELECT id_area FROM areas WHERE nombre_area='Mantenimiento'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='lmamani'), (SELECT id_almacen FROM almacenes WHERE codigo_almacen='ALM-SUP-001'), (SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'Luis Mamani Flores', '2026-07-08', '2026-07-08', 'NORMAL', 'ENTREGADO_COMPLETO', TRUE, 'evidencia_des_0003.pdf', 'Despacho completo de aceite.', 2);

INSERT INTO despacho_detalles (
    id_despacho, id_insumo, cantidad_solicitada, cantidad_aprobada, cantidad_entregada,
    estado_conformidad, observacion
) VALUES
((SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-CAS-001'), 20, 20, 20, 'CONFORME', 'Entrega conforme.'),
((SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0001'), (SELECT id_insumo FROM insumos WHERE codigo_interno='SEG-GUA-001'), 60, 60, 60, 'CONFORME', 'Entrega conforme.'),
((SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0002'), (SELECT id_insumo FROM insumos WHERE codigo_interno='PER-BRO-038'), 15, 15, 15, 'CONFORME', 'Entrega conforme.'),
((SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0003'), (SELECT id_insumo FROM insumos WHERE codigo_interno='LUB-ACE-001'), 100, 100, 100, 'CONFORME', 'Entrega conforme.');

-- Actualización de estado final de pedidos
UPDATE pedidos SET estado_pedido='ENTREGADO_COMPLETO', estado_atencion='ATENDIDO_TOTAL', fecha_actualizacion=NOW()
WHERE numero_pedido IN ('PED-2026-0001', 'PED-2026-0002', 'PED-2026-0003');

-- Notificaciones de ejemplo
INSERT INTO notificaciones (tipo_notificacion, titulo, mensaje, id_usuario_destinatario, modulo_relacionado, id_registro_relacionado, prioridad, estado_notificacion, usuario_genera) VALUES
('PEDIDO_APROBADO', 'Pedido aprobado', 'El pedido PED-2026-0001 fue aprobado para atención.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='cquispe'), 'Pedidos', (SELECT id_pedido FROM pedidos WHERE numero_pedido='PED-2026-0001'), 'ALTA', 'NO_LEIDA', 3),
('COMPRA_RECIBIDA_COMPLETA', 'Compra recibida', 'La compra OC-2026-0002 fue recibida completamente.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='avargas'), 'Compras', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0002'), 'MEDIA', 'NO_LEIDA', 2),
('DESPACHO_REALIZADO', 'Despacho realizado', 'El despacho DES-2026-0003 fue entregado completamente.', (SELECT id_usuario FROM usuarios WHERE nombre_usuario='lmamani'), 'Despachos', (SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0003'), 'MEDIA', 'NO_LEIDA', 2);

-- Auditoría de ejemplo
INSERT INTO auditorias (id_usuario, accion_realizada, tipo_accion, modulo_afectado, tabla_afectada, id_registro_afectado, registro_anterior, registro_nuevo, direccion_ip, navegador_dispositivo, motivo_cambio, observaciones) VALUES
((SELECT id_usuario FROM usuarios WHERE nombre_usuario='jperez'), 'Creación de usuario administrador', 'CREAR', 'Usuarios', 'usuarios', 1, NULL, '{"usuario":"jperez","estado":"ACTIVO"}', '127.0.0.1', 'DBeaver / PostgreSQL', 'Configuración inicial', 'Registro de auditoría inicial.'),
((SELECT id_usuario FROM usuarios WHERE nombre_usuario='avargas'), 'Registro de orden de compra OC-2026-0002', 'REGISTRAR_COMPRA', 'Compras', 'ordenes_compra', (SELECT id_orden_compra FROM ordenes_compra WHERE numero_orden='OC-2026-0002'), NULL, '{"numero_orden":"OC-2026-0002","estado":"RECIBIDA_COMPLETA"}', '127.0.0.1', 'DBeaver / PostgreSQL', 'Compra para pedido aprobado', 'Orden de compra registrada.'),
((SELECT id_usuario FROM usuarios WHERE nombre_usuario='mcondori'), 'Registro de despacho DES-2026-0003', 'REALIZAR_DESPACHO', 'Inventario y Despachos', 'despachos', (SELECT id_despacho FROM despachos WHERE numero_despacho='DES-2026-0003'), NULL, '{"numero_despacho":"DES-2026-0003","estado":"ENTREGADO_COMPLETO"}', '127.0.0.1', 'DBeaver / PostgreSQL', 'Entrega de insumo solicitado', 'Despacho registrado correctamente.');

-- =============================================================================
-- 13. CONSULTAS ÚTILES PARA PROBAR EN DBEAVER
-- =============================================================================

-- 1) Ver resumen del dashboard
SELECT * FROM v_dashboard_resumen;

-- 2) Ver stock actual por almacén
SELECT * FROM v_stock_actual ORDER BY nombre_almacen, nombre_insumo;

-- 3) Ver insumos con stock bajo
SELECT * FROM v_stock_bajo ORDER BY nombre_insumo;

-- 4) Ver kardex completo
SELECT * FROM v_kardex ORDER BY fecha_movimiento, numero_movimiento;

-- 5) Ver pedidos con solicitante y área
SELECT
    p.numero_pedido,
    u.nombre_completo AS solicitante,
    a.nombre_area,
    p.fecha_pedido,
    p.fecha_requerida,
    p.prioridad,
    p.estado_pedido,
    p.estado_aprobacion,
    p.estado_atencion
FROM pedidos p
INNER JOIN usuarios u ON u.id_usuario = p.id_usuario_solicitante
INNER JOIN areas a ON a.id_area = p.id_area_solicitante
ORDER BY p.numero_pedido;

-- 6) Ver detalle de pedidos
SELECT
    p.numero_pedido,
    i.codigo_interno,
    i.nombre_insumo,
    pd.cantidad_solicitada,
    pd.cantidad_aprobada,
    pd.cantidad_despachada,
    pd.cantidad_pendiente
FROM pedido_detalles pd
INNER JOIN pedidos p ON p.id_pedido = pd.id_pedido
INNER JOIN insumos i ON i.id_insumo = pd.id_insumo
ORDER BY p.numero_pedido, i.nombre_insumo;

-- 7) Ver compras por proveedor
SELECT * FROM v_compras_por_proveedor ORDER BY monto_total_comprado DESC;

-- 8) Ver comprobantes registrados
SELECT
    cc.numero_comprobante,
    cc.tipo_comprobante,
    pr.razon_social AS proveedor,
    oc.numero_orden,
    cc.monto_total,
    cc.moneda,
    cc.estado_comprobante
FROM comprobantes_compra cc
INNER JOIN proveedores pr ON pr.id_proveedor = cc.id_proveedor
INNER JOIN ordenes_compra oc ON oc.id_orden_compra = cc.id_orden_compra
ORDER BY cc.numero_comprobante;

-- 9) Ver despachos realizados
SELECT
    d.numero_despacho,
    p.numero_pedido,
    a.nombre_area,
    d.persona_recibe,
    d.fecha_real_entrega,
    d.estado_despacho
FROM despachos d
INNER JOIN pedidos p ON p.id_pedido = d.id_pedido
INNER JOIN areas a ON a.id_area = d.id_area_solicitante
ORDER BY d.numero_despacho;

-- 10) Ver usuarios, roles y áreas
SELECT
    u.nombre_completo,
    u.nombre_usuario,
    u.correo,
    r.nombre_rol,
    a.nombre_area,
    u.estado
FROM usuarios u
INNER JOIN roles r ON r.id_rol = u.id_rol
INNER JOIN areas a ON a.id_area = u.id_area
ORDER BY u.id_usuario;

-- 11) Ver permisos por rol
SELECT
    r.nombre_rol,
    p.modulo,
    p.codigo_permiso,
    p.descripcion
FROM roles_permisos rp
INNER JOIN roles r ON r.id_rol = rp.id_rol
INNER JOIN permisos p ON p.id_permiso = rp.id_permiso
ORDER BY r.nombre_rol, p.modulo, p.codigo_permiso;

-- 12) Ver auditoría
SELECT
    au.fecha_hora,
    u.nombre_completo AS usuario,
    au.tipo_accion,
    au.modulo_afectado,
    au.accion_realizada,
    au.tabla_afectada,
    au.id_registro_afectado
FROM auditorias au
LEFT JOIN usuarios u ON u.id_usuario = au.id_usuario
ORDER BY au.fecha_hora DESC;

-- FIN DEL SCRIPT
