/*
================================================================================
 BASE DE DATOS: mineria
 ESQUEMA: public
 SISTEMA: Sistema web full stack para la gestión logística de insumos y compras
          en operación mina
 MOTOR: PostgreSQL
 NOTA: APA 7ma edición aplica a la documentación académica. Para la base de datos
       se aplica normalización relacional hasta 3FN, con tablas separadas,
       claves primarias, claves foráneas, catálogos, restricciones y vistas.
       Esta version limpia solo agrega la configuracion minima de acceso.
================================================================================

INSTRUCCIONES EN DBEAVER
1) Crear una base de datos llamada: mineria
2) Conectarse a la base de datos mineria.
3) Abrir este script SQL y ejecutarlo completo.
4) Todo se creará en el esquema public.
*/

SET search_path TO public;
SET TIME ZONE 'America/La_Paz';

-- =============================================================================
-- 1. LIMPIEZA ORDENADA DEL ESQUEMA PUBLIC
-- =============================================================================
DROP VIEW IF EXISTS v_dashboard_resumen CASCADE;
DROP VIEW IF EXISTS v_compras_por_proveedor CASCADE;
DROP VIEW IF EXISTS v_pedidos_por_estado CASCADE;
DROP VIEW IF EXISTS v_kardex CASCADE;
DROP VIEW IF EXISTS v_stock_bajo CASCADE;
DROP VIEW IF EXISTS v_stock_actual CASCADE;

DROP TABLE IF EXISTS auditorias CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS despacho_detalles CASCADE;
DROP TABLE IF EXISTS despachos CASCADE;
DROP TABLE IF EXISTS comprobantes_compra CASCADE;
DROP TABLE IF EXISTS recepcion_detalles CASCADE;
DROP TABLE IF EXISTS recepciones_compra CASCADE;
DROP TABLE IF EXISTS orden_compra_detalles CASCADE;
DROP TABLE IF EXISTS ordenes_compra CASCADE;
DROP TABLE IF EXISTS aprobaciones_pedido CASCADE;
DROP TABLE IF EXISTS pedido_detalles CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS inventarios CASCADE;
DROP TABLE IF EXISTS politicas_stock CASCADE;
DROP TABLE IF EXISTS proveedor_insumo CASCADE;
DROP TABLE IF EXISTS insumos CASCADE;
DROP TABLE IF EXISTS almacenes CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS unidades_medida CASCADE;
DROP TABLE IF EXISTS tipos_insumo CASCADE;
DROP TABLE IF EXISTS categorias_insumo CASCADE;
DROP TABLE IF EXISTS roles_permisos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS permisos CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS areas CASCADE;

DROP FUNCTION IF EXISTS fn_recepcion_actualiza_inventario();
DROP FUNCTION IF EXISTS fn_despacho_actualiza_inventario();

-- =============================================================================
-- 2. CATÁLOGOS BASE
-- =============================================================================
CREATE TABLE areas (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_permiso VARCHAR(80) NOT NULL UNIQUE,
    modulo VARCHAR(80) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles_permisos (
    id_rol INTEGER NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
    id_permiso INTEGER NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area INTEGER NOT NULL REFERENCES areas(id_area),
    id_rol INTEGER NOT NULL REFERENCES roles(id_rol),
    nombre_completo VARCHAR(150) NOT NULL,
    nombre_usuario VARCHAR(80) NOT NULL UNIQUE,
    correo VARCHAR(150) UNIQUE,
    cedula_identidad VARCHAR(30),
    complemento_ci VARCHAR(10),
    expedido_ci VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    cargo VARCHAR(100),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    ultimo_inicio_sesion TIMESTAMPTZ,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0 CHECK (intentos_fallidos >= 0),
    cambio_obligatorio BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE categorias_insumo (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE tipos_insumo (
    id_tipo_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE unidades_medida (
    id_unidad_medida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_unidad VARCHAR(80) NOT NULL UNIQUE,
    abreviatura VARCHAR(20) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 3. MÓDULOS MAESTROS: ALMACENES, PROVEEDORES E INSUMOS
-- =============================================================================
CREATE TABLE almacenes (
    id_almacen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_almacen VARCHAR(30) NOT NULL UNIQUE,
    nombre_almacen VARCHAR(120) NOT NULL,
    tipo_almacen VARCHAR(40) NOT NULL CHECK (tipo_almacen IN (
        'SUPERFICIE', 'SUBTERRANEO', 'POLVORIN', 'SEGURIDAD_INDUSTRIAL',
        'HERRAMIENTAS_REPUESTOS', 'COMBUSTIBLE', 'LUBRICANTES', 'TEMPORAL'
    )),
    ubicacion VARCHAR(180) NOT NULL,
    id_responsable_principal INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    id_responsable_suplente INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    telefono_contacto VARCHAR(30),
    horario_atencion VARCHAR(120),
    descripcion TEXT,
    capacidad_maxima NUMERIC(14,2) CHECK (capacidad_maxima IS NULL OR capacidad_maxima >= 0),
    capacidad_minima_recomendada NUMERIC(14,2) CHECK (capacidad_minima_recomendada IS NULL OR capacidad_minima_recomendada >= 0),
    tipo_almacenamiento VARCHAR(120),
    observaciones_seguridad TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_proveedor VARCHAR(30) NOT NULL UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    nombre_comercial VARCHAR(150),
    nit VARCHAR(30) NOT NULL UNIQUE,
    rubro VARCHAR(120) NOT NULL,
    tipo_insumos_provee TEXT,
    persona_contacto VARCHAR(120),
    cargo_contacto VARCHAR(100),
    telefono VARCHAR(30),
    celular_whatsapp VARCHAR(30),
    correo VARCHAR(150),
    direccion TEXT,
    ciudad VARCHAR(80),
    condiciones_pago VARCHAR(120),
    forma_pago VARCHAR(120),
    tiempo_estimado_entrega VARCHAR(80),
    calificacion NUMERIC(3,2) CHECK (calificacion IS NULL OR calificacion BETWEEN 0 AND 5),
    documentacion_vigente BOOLEAN DEFAULT TRUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE insumos (
    id_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL REFERENCES categorias_insumo(id_categoria),
    id_tipo_insumo INTEGER NOT NULL REFERENCES tipos_insumo(id_tipo_insumo),
    id_unidad_medida INTEGER NOT NULL REFERENCES unidades_medida(id_unidad_medida),
    id_unidad_medida_secundaria INTEGER REFERENCES unidades_medida(id_unidad_medida),
    codigo_interno VARCHAR(40) NOT NULL UNIQUE,
    codigo_barra_qr VARCHAR(80) UNIQUE,
    nombre_insumo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    presentacion VARCHAR(100),
    precio_referencial NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (precio_referencial >= 0),
    stock_minimo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    ubicacion_sugerida VARCHAR(120),
    requiere_control_especial BOOLEAN NOT NULL DEFAULT FALSE,
    es_peligroso_inflamable BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_vencimiento DATE,
    imagen_url VARCHAR(255),
    ficha_tecnica_url VARCHAR(255),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ELIMINADO')),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE proveedor_insumo (
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo) ON DELETE CASCADE,
    precio_referencial NUMERIC(14,2) CHECK (precio_referencial IS NULL OR precio_referencial >= 0),
    tiempo_entrega_dias INTEGER CHECK (tiempo_entrega_dias IS NULL OR tiempo_entrega_dias >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    PRIMARY KEY (id_proveedor, id_insumo)
);

-- =============================================================================
-- 4. INVENTARIO, POLÍTICAS DE STOCK Y MOVIMIENTOS
-- =============================================================================
CREATE TABLE politicas_stock (
    id_politica_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo) ON DELETE CASCADE,
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen) ON DELETE CASCADE,
    stock_minimo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    stock_maximo NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_maximo >= 0),
    stock_seguridad NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_seguridad >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    UNIQUE (id_insumo, id_almacen),
    CHECK (stock_maximo = 0 OR stock_maximo >= stock_minimo)
);

CREATE TABLE inventarios (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    stock_fisico NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_fisico >= 0),
    stock_reservado NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (stock_reservado >= 0),
    stock_disponible NUMERIC(14,2) GENERATED ALWAYS AS (stock_fisico - stock_reservado) STORED,
    costo_promedio NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (costo_promedio >= 0),
    valor_total_stock NUMERIC(14,2) GENERATED ALWAYS AS (stock_fisico * costo_promedio) STORED,
    lote VARCHAR(80),
    numero_serie VARCHAR(80),
    fecha_vencimiento DATE,
    ubicacion_interna VARCHAR(120),
    estado_stock VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado_stock IN ('DISPONIBLE', 'RESERVADO', 'AGOTADO', 'OBSERVADO')),
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    UNIQUE (id_insumo, id_almacen),
    CHECK (stock_reservado <= stock_fisico)
);

CREATE TABLE movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_movimiento VARCHAR(40) NOT NULL UNIQUE,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo_movimiento VARCHAR(40) NOT NULL CHECK (tipo_movimiento IN (
        'ENTRADA_COMPRA', 'SALIDA_DESPACHO', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO',
        'DEVOLUCION', 'TRANSFERENCIA_SALIDA', 'TRANSFERENCIA_ENTRADA'
    )),
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen_origen INTEGER REFERENCES almacenes(id_almacen),
    id_almacen_destino INTEGER REFERENCES almacenes(id_almacen),
    id_despacho INTEGER,
    id_recepcion INTEGER,
    codigo_referencia VARCHAR(60),
    cantidad NUMERIC(14,2) NOT NULL CHECK (cantidad > 0),
    costo_unitario NUMERIC(14,2) DEFAULT 0 CHECK (costo_unitario >= 0),
    motivo TEXT NOT NULL,
    documento_respaldo VARCHAR(255),
    usuario_responsable INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 5. PEDIDOS Y APROBACIONES
-- =============================================================================
CREATE TABLE pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(40) NOT NULL UNIQUE,
    id_usuario_solicitante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_area_solicitante INTEGER NOT NULL REFERENCES areas(id_area),
    fecha_pedido TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_requerida TIMESTAMPTZ NOT NULL,
    tipo_pedido VARCHAR(30) NOT NULL CHECK (tipo_pedido IN ('NORMAL', 'URGENTE', 'REPOSICION', 'EMERGENCIA', 'MANTENIMIENTO', 'OPERACION')),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    justificacion TEXT NOT NULL,
    estado_pedido VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pedido IN (
        'PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO', 'EN_COMPRA',
        'EN_DESPACHO', 'ENTREGADO_PARCIAL', 'ENTREGADO_COMPLETO', 'CANCELADO'
    )),
    estado_aprobacion VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO')),
    estado_atencion VARCHAR(40) NOT NULL DEFAULT 'SIN_ATENDER' CHECK (estado_atencion IN ('SIN_ATENDER', 'EN_PROCESO', 'ATENDIDO_PARCIAL', 'ATENDIDO_TOTAL')),
    id_proveedor_sugerido INTEGER REFERENCES proveedores(id_proveedor),
    archivo_adjunto VARCHAR(255),
    centro_costo VARCHAR(80),
    lugar_uso VARCHAR(120),
    turno_guardia VARCHAR(80),
    observaciones TEXT,
    id_usuario_revisor INTEGER REFERENCES usuarios(id_usuario),
    fecha_revision TIMESTAMPTZ,
    motivo_rechazo TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,
    creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE pedido_detalles (
    id_pedido_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_aprobada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_aprobada >= 0),
    cantidad_despachada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_despachada >= 0),
    cantidad_pendiente NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_aprobada - cantidad_despachada) STORED,
    observacion TEXT,
    CHECK (cantidad_aprobada <= cantidad_solicitada),
    CHECK (cantidad_despachada <= cantidad_aprobada)
);

CREATE TABLE reservas_stock (
    id_reserva_stock INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario INTEGER NOT NULL REFERENCES inventarios(id_inventario) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    id_almacen INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_pedido_detalle INTEGER NOT NULL REFERENCES pedido_detalles(id_pedido_detalle) ON DELETE CASCADE,
    cantidad_reservada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_reservada >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'LIBERADA')),
    fecha_reserva TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_liberacion TIMESTAMPTZ,
    UNIQUE (id_pedido_detalle, id_almacen)
);

CREATE TABLE aprobaciones_pedido (
    id_aprobacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
    id_usuario_aprobador INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    nivel_aprobacion INTEGER NOT NULL DEFAULT 1 CHECK (nivel_aprobacion >= 1),
    fecha_aprobacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_aprobacion VARCHAR(30) NOT NULL CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO')),
    observaciones TEXT,
    motivo_rechazo TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 6. COMPRAS, RECEPCIONES Y COMPROBANTES
-- =============================================================================
CREATE TABLE ordenes_compra (
    id_orden_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden VARCHAR(40) NOT NULL UNIQUE,
    codigo_correlativo VARCHAR(40) NOT NULL UNIQUE,
    id_pedido INTEGER REFERENCES pedidos(id_pedido),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_estimada_entrega TIMESTAMPTZ,
    condicion_pago VARCHAR(120),
    forma_pago VARCHAR(120),
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pago IN ('PENDIENTE', 'PAGADO_PARCIAL', 'PAGADO_COMPLETO', 'ANULADO')),
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    descuento NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    total_final NUMERIC(14,2) GENERATED ALWAYS AS (subtotal - descuento) STORED,
    estado_compra VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_compra IN ('PENDIENTE', 'EN_PROCESO', 'RECIBIDA_PARCIAL', 'RECIBIDA_COMPLETA', 'ANULADA')),
    observaciones TEXT,
    usuario_genera INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

CREATE TABLE orden_compra_detalles (
    id_orden_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_comprada NUMERIC(14,2) NOT NULL CHECK (cantidad_comprada > 0),
    precio_unitario NUMERIC(14,2) NOT NULL CHECK (precio_unitario >= 0),
    subtotal NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_comprada * precio_unitario) STORED,
    observacion TEXT
);

CREATE TABLE recepciones_compra (
    id_recepcion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_recepcion VARCHAR(40) NOT NULL UNIQUE,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    id_almacen_destino INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    fecha_estimada_recepcion TIMESTAMPTZ,
    fecha_real_recepcion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_responsable_recepcion INTEGER REFERENCES usuarios(id_usuario),
    estado_recepcion VARCHAR(40) NOT NULL CHECK (estado_recepcion IN ('PENDIENTE', 'RECIBIDA_PARCIAL', 'RECIBIDA_COMPLETA', 'OBSERVADA', 'RECHAZADA')),
    documento_respaldo VARCHAR(255),
    observaciones TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE recepcion_detalles (
    id_recepcion_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recepcion INTEGER NOT NULL REFERENCES recepciones_compra(id_recepcion) ON DELETE CASCADE,
    id_orden_detalle INTEGER NOT NULL REFERENCES orden_compra_detalles(id_orden_detalle),
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_comprada NUMERIC(14,2) NOT NULL CHECK (cantidad_comprada > 0),
    cantidad_recibida NUMERIC(14,2) NOT NULL CHECK (cantidad_recibida >= 0),
    cantidad_aceptada NUMERIC(14,2) NOT NULL CHECK (cantidad_aceptada >= 0),
    cantidad_rechazada NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_rechazada >= 0),
    cantidad_faltante NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cantidad_faltante >= 0),
    motivo_rechazo TEXT,
    estado_conformidad VARCHAR(30) NOT NULL CHECK (estado_conformidad IN ('CONFORME', 'OBSERVADO', 'RECHAZADO')),
    observaciones TEXT,
    CHECK (cantidad_aceptada + cantidad_rechazada <= cantidad_recibida)
);

CREATE TABLE comprobantes_compra (
    id_comprobante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_comprobante VARCHAR(60) NOT NULL UNIQUE,
    tipo_comprobante VARCHAR(40) NOT NULL CHECK (tipo_comprobante IN ('FACTURA', 'RECIBO', 'NOTA_VENTA', 'COMPROBANTE_INTERNO', 'OTRO')),
    fecha_comprobante TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    nit_proveedor VARCHAR(30) NOT NULL,
    id_orden_compra INTEGER NOT NULL REFERENCES ordenes_compra(id_orden_compra),
    monto_subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_subtotal >= 0),
    monto_descuento NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
    monto_total NUMERIC(14,2) GENERATED ALWAYS AS (monto_subtotal - monto_descuento) STORED,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    estado_comprobante VARCHAR(30) NOT NULL DEFAULT 'REGISTRADO' CHECK (estado_comprobante IN ('REGISTRADO', 'OBSERVADO', 'ANULADO')),
    archivo_comprobante VARCHAR(255),
    observaciones TEXT,
    usuario_registra INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 7. DESPACHOS
-- =============================================================================
CREATE TABLE despachos (
    id_despacho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_despacho VARCHAR(40) NOT NULL UNIQUE,
    id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido),
    id_area_solicitante INTEGER NOT NULL REFERENCES areas(id_area),
    id_usuario_solicitante INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    id_almacen_salida INTEGER NOT NULL REFERENCES almacenes(id_almacen),
    id_responsable_almacen INTEGER REFERENCES usuarios(id_usuario),
    persona_recibe VARCHAR(150) NOT NULL,
    fecha_programada_entrega DATE,
    fecha_real_entrega TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo_despacho VARCHAR(30) NOT NULL CHECK (tipo_despacho IN ('NORMAL', 'URGENTE', 'PARCIAL', 'DEVOLUCION', 'REPOSICION')),
    estado_despacho VARCHAR(40) NOT NULL CHECK (estado_despacho IN (
        'PENDIENTE', 'PENDIENTE_ENTREGA', 'PREPARADO',
        'ENTREGADO_PARCIAL', 'ENTREGADO_COMPLETO', 'CANCELADO', 'OBSERVADO'
    )),
    confirmacion_recepcion BOOLEAN NOT NULL DEFAULT FALSE,
    evidencia_entrega VARCHAR(255),
    observaciones TEXT,
    usuario_registra INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE despacho_detalles (
    id_despacho_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_despacho INTEGER NOT NULL REFERENCES despachos(id_despacho) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumos(id_insumo),
    cantidad_solicitada NUMERIC(14,2) NOT NULL CHECK (cantidad_solicitada > 0),
    cantidad_aprobada NUMERIC(14,2) NOT NULL CHECK (cantidad_aprobada >= 0),
    cantidad_entregada NUMERIC(14,2) NOT NULL CHECK (cantidad_entregada >= 0),
    cantidad_pendiente NUMERIC(14,2) GENERATED ALWAYS AS (cantidad_aprobada - cantidad_entregada) STORED,
    estado_conformidad VARCHAR(30) NOT NULL CHECK (estado_conformidad IN ('CONFORME', 'OBSERVADO', 'RECHAZADO')),
    observacion TEXT,
    CHECK (cantidad_entregada <= cantidad_aprobada)
);

-- =============================================================================
-- 8. NOTIFICACIONES Y AUDITORÍA
-- =============================================================================
CREATE TABLE notificaciones (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_notificacion VARCHAR(50) NOT NULL CHECK (tipo_notificacion IN (
        'STOCK_BAJO', 'INSUMO_SIN_STOCK', 'PEDIDO_CREADO', 'PEDIDO_APROBADO',
        'PEDIDO_RECHAZADO', 'PEDIDO_OBSERVADO', 'PEDIDO_EN_COMPRA', 'COMPRA_REGISTRADA',
        'COMPRA_RECIBIDA_PARCIAL', 'COMPRA_RECIBIDA_COMPLETA', 'DESPACHO_REALIZADO',
        'COMPROBANTE_REGISTRADO', 'COMPROBANTE_OBSERVADO', 'TRANSFERENCIA_REGISTRADA',
        'DEVOLUCION_REGISTRADA', 'USUARIO_CREADO', 'AUDITORIA_IMPORTANTE'
    )),
    titulo VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    id_usuario_destinatario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    modulo_relacionado VARCHAR(80),
    id_registro_relacionado INTEGER,
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    estado_notificacion VARCHAR(20) NOT NULL DEFAULT 'NO_LEIDA' CHECK (estado_notificacion IN ('NO_LEIDA', 'LEIDA', 'ARCHIVADA')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_lectura TIMESTAMPTZ,
    usuario_genera INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE auditorias (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    accion_realizada VARCHAR(150) NOT NULL,
    tipo_accion VARCHAR(40) NOT NULL CHECK (tipo_accion IN (
        'CREAR', 'EDITAR', 'ELIMINAR', 'ACTIVAR', 'DESACTIVAR', 'APROBAR', 'RECHAZAR',
        'ANULAR', 'LOGIN', 'LOGOUT', 'CONSULTAR',
        'REGISTRAR_COMPRA', 'REGISTRAR_RECEPCION', 'REGISTRAR_COMPROBANTE',
        'REALIZAR_DESPACHO', 'AJUSTAR_INVENTARIO', 'INICIAR_SESION', 'CERRAR_SESION',
        'CAMBIAR_CONTRASENA', 'CAMBIAR_PERMISOS', 'ACCESO_DENEGADO'
    )),
    modulo_afectado VARCHAR(80) NOT NULL,
    tabla_afectada VARCHAR(80),
    id_registro_afectado INTEGER,
    registro_anterior JSONB,
    registro_nuevo JSONB,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    direccion_ip VARCHAR(60),
    navegador_dispositivo VARCHAR(255),
    motivo_cambio TEXT,
    observaciones TEXT
);

-- =============================================================================
-- 9. ÍNDICES PARA MEJORAR CONSULTAS
-- =============================================================================
CREATE INDEX idx_usuarios_area ON usuarios(id_area);
CREATE INDEX idx_usuarios_rol ON usuarios(id_rol);
CREATE UNIQUE INDEX ux_usuarios_cedula_identidad
  ON usuarios(cedula_identidad)
  WHERE cedula_identidad IS NOT NULL AND btrim(cedula_identidad) <> '';
CREATE INDEX idx_insumos_categoria ON insumos(id_categoria);
CREATE INDEX idx_insumos_tipo ON insumos(id_tipo_insumo);
CREATE INDEX idx_inventarios_insumo ON inventarios(id_insumo);
CREATE INDEX idx_inventarios_almacen ON inventarios(id_almacen);
CREATE INDEX idx_movimientos_insumo_fecha ON movimientos_inventario(id_insumo, fecha_movimiento);
CREATE INDEX idx_movimientos_id_despacho ON movimientos_inventario(id_despacho);
CREATE INDEX idx_movimientos_id_recepcion ON movimientos_inventario(id_recepcion);
CREATE INDEX idx_movimientos_codigo_referencia ON movimientos_inventario(codigo_referencia);
CREATE INDEX idx_pedidos_estado ON pedidos(estado_pedido);
CREATE INDEX idx_pedidos_area ON pedidos(id_area_solicitante);
CREATE INDEX idx_ordenes_proveedor ON ordenes_compra(id_proveedor);
CREATE INDEX idx_despachos_pedido ON despachos(id_pedido);
CREATE INDEX idx_notificaciones_usuario_estado ON notificaciones(id_usuario_destinatario, estado_notificacion);
CREATE INDEX idx_auditorias_usuario_fecha ON auditorias(id_usuario, fecha_hora);
CREATE INDEX idx_almacenes_estado_no_eliminado ON almacenes(estado) WHERE estado <> 'ELIMINADO';
CREATE INDEX idx_usuarios_estado_no_eliminado ON usuarios(estado) WHERE estado <> 'ELIMINADO';
CREATE INDEX idx_proveedores_estado_no_eliminado ON proveedores(estado) WHERE estado <> 'ELIMINADO';
CREATE INDEX idx_insumos_estado_no_eliminado ON insumos(estado) WHERE estado <> 'ELIMINADO';

ALTER TABLE movimientos_inventario
  ADD CONSTRAINT movimientos_inventario_id_despacho_fkey
  FOREIGN KEY (id_despacho) REFERENCES despachos(id_despacho) ON DELETE SET NULL;

ALTER TABLE movimientos_inventario
  ADD CONSTRAINT movimientos_inventario_id_recepcion_fkey
  FOREIGN KEY (id_recepcion) REFERENCES recepciones_compra(id_recepcion) ON DELETE SET NULL;

-- =============================================================================
-- 10. FUNCIONES Y TRIGGERS PARA ACTUALIZACIÓN AUTOMÁTICA DE INVENTARIO
-- =============================================================================
CREATE OR REPLACE FUNCTION fn_recepcion_actualiza_inventario()
RETURNS TRIGGER AS $$
DECLARE
    v_almacen INTEGER;
    v_usuario INTEGER;
    v_costo NUMERIC(14,2);
    v_numero_recepcion VARCHAR(40);
BEGIN
    IF NEW.cantidad_aceptada > 0 THEN
        SELECT rc.id_almacen_destino, rc.id_responsable_recepcion, rc.numero_recepcion
        INTO v_almacen, v_usuario, v_numero_recepcion
        FROM recepciones_compra rc
        WHERE rc.id_recepcion = NEW.id_recepcion;

        SELECT ocd.precio_unitario
        INTO v_costo
        FROM orden_compra_detalles ocd
        WHERE ocd.id_orden_detalle = NEW.id_orden_detalle;

        INSERT INTO inventarios (
            id_insumo, id_almacen, stock_fisico, stock_reservado,
            costo_promedio, fecha_ultima_actualizacion, creado_por
        )
        VALUES (
            NEW.id_insumo, v_almacen, NEW.cantidad_aceptada, 0,
            COALESCE(v_costo, 0), NOW(), v_usuario
        )
        ON CONFLICT (id_insumo, id_almacen)
        DO UPDATE SET
            costo_promedio = CASE
                WHEN (inventarios.stock_fisico + EXCLUDED.stock_fisico) > 0 THEN
                    ROUND(((inventarios.stock_fisico * inventarios.costo_promedio) +
                           (EXCLUDED.stock_fisico * EXCLUDED.costo_promedio)) /
                          (inventarios.stock_fisico + EXCLUDED.stock_fisico), 2)
                ELSE EXCLUDED.costo_promedio
            END,
            stock_fisico = inventarios.stock_fisico + EXCLUDED.stock_fisico,
            estado_stock = 'DISPONIBLE',
            fecha_ultima_actualizacion = NOW(),
            actualizado_por = v_usuario;

        INSERT INTO movimientos_inventario (
            numero_movimiento, tipo_movimiento, id_insumo, id_almacen_destino,
            cantidad, costo_unitario, motivo, documento_respaldo, usuario_responsable, observaciones
        )
        VALUES (
            'MOV-REC-' || NEW.id_recepcion_detalle,
            'ENTRADA_COMPRA',
            NEW.id_insumo,
            v_almacen,
            NEW.cantidad_aceptada,
            COALESCE(v_costo, 0),
            'Entrada automática por recepción de compra',
            v_numero_recepcion,
            v_usuario,
            'Movimiento generado automáticamente desde recepción de compra.'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_recepcion_actualiza_inventario
AFTER INSERT ON recepcion_detalles
FOR EACH ROW
EXECUTE FUNCTION fn_recepcion_actualiza_inventario();

CREATE OR REPLACE FUNCTION fn_despacho_actualiza_inventario()
RETURNS TRIGGER AS $$
DECLARE
    v_almacen INTEGER;
    v_usuario INTEGER;
    v_id_pedido INTEGER;
    v_numero_despacho VARCHAR(40);
    v_stock_fisico NUMERIC(14,2);
    v_stock_reservado NUMERIC(14,2);
    v_reservado_pedido NUMERIC(14,2);
    v_costo NUMERIC(14,2);
BEGIN
    IF NEW.cantidad_entregada > 0 THEN
        SELECT d.id_almacen_salida, d.id_responsable_almacen, d.id_pedido, d.numero_despacho
        INTO v_almacen, v_usuario, v_id_pedido, v_numero_despacho
        FROM despachos d
        WHERE d.id_despacho = NEW.id_despacho;

        SELECT i.stock_fisico, i.stock_reservado, i.costo_promedio
        INTO v_stock_fisico, v_stock_reservado, v_costo
        FROM inventarios i
        WHERE i.id_insumo = NEW.id_insumo
          AND i.id_almacen = v_almacen
        FOR UPDATE;

        SELECT COALESCE(SUM(rs.cantidad_reservada), 0)
        INTO v_reservado_pedido
        FROM reservas_stock rs
        WHERE rs.id_pedido = v_id_pedido
          AND rs.id_insumo = NEW.id_insumo
          AND rs.id_almacen = v_almacen
          AND rs.estado = 'ACTIVA';

        IF COALESCE(v_stock_fisico, 0) < NEW.cantidad_entregada
           OR (
             v_reservado_pedido < NEW.cantidad_entregada
             AND COALESCE(v_stock_fisico, 0) - COALESCE(v_stock_reservado, 0) < NEW.cantidad_entregada
           ) THEN
            RAISE EXCEPTION 'Stock insuficiente para el insumo %. Stock fisico: %, reservado para pedido: %, cantidad solicitada: %',
                NEW.id_insumo, COALESCE(v_stock_fisico, 0), COALESCE(v_reservado_pedido, 0), NEW.cantidad_entregada;
        END IF;

        UPDATE inventarios
        SET stock_fisico = stock_fisico - NEW.cantidad_entregada,
            estado_stock = CASE
                WHEN stock_fisico - NEW.cantidad_entregada = 0 THEN 'AGOTADO'
                WHEN stock_reservado > 0 THEN 'RESERVADO'
                ELSE 'DISPONIBLE'
            END,
            fecha_ultima_actualizacion = NOW(),
            actualizado_por = v_usuario
        WHERE id_insumo = NEW.id_insumo
          AND id_almacen = v_almacen;

        INSERT INTO movimientos_inventario (
            numero_movimiento, tipo_movimiento, id_insumo, id_almacen_origen,
            cantidad, costo_unitario, motivo, documento_respaldo, usuario_responsable, observaciones
        )
        VALUES (
            'MOV-DES-' || NEW.id_despacho_detalle,
            'SALIDA_DESPACHO',
            NEW.id_insumo,
            v_almacen,
            NEW.cantidad_entregada,
            COALESCE(v_costo, 0),
            'Salida automática por despacho de insumos',
            v_numero_despacho,
            v_usuario,
            'Movimiento generado automáticamente desde despacho.'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_despacho_actualiza_inventario
AFTER INSERT ON despacho_detalles
FOR EACH ROW
EXECUTE FUNCTION fn_despacho_actualiza_inventario();

-- =============================================================================
-- 11. VISTAS DE REPORTES Y DASHBOARD
-- =============================================================================
CREATE VIEW v_stock_actual AS
SELECT
    i.id_inventario,
    ins.codigo_interno,
    ins.nombre_insumo,
    c.nombre_categoria,
    ti.nombre_tipo,
    um.abreviatura AS unidad_medida,
    a.codigo_almacen,
    a.nombre_almacen,
    a.tipo_almacen,
    i.stock_fisico,
    i.stock_reservado,
    i.stock_disponible,
    ins.stock_minimo,
    COALESCE(ps.stock_maximo, 0) AS stock_maximo,
    COALESCE(ps.stock_seguridad, 0) AS stock_seguridad,
    i.costo_promedio,
    i.valor_total_stock,
    i.estado_stock,
    i.fecha_ultima_actualizacion
FROM inventarios i
INNER JOIN insumos ins ON ins.id_insumo = i.id_insumo
INNER JOIN categorias_insumo c ON c.id_categoria = ins.id_categoria
INNER JOIN tipos_insumo ti ON ti.id_tipo_insumo = ins.id_tipo_insumo
INNER JOIN unidades_medida um ON um.id_unidad_medida = ins.id_unidad_medida
INNER JOIN almacenes a ON a.id_almacen = i.id_almacen
LEFT JOIN politicas_stock ps ON ps.id_insumo = i.id_insumo AND ps.id_almacen = i.id_almacen;

CREATE VIEW v_stock_bajo AS
SELECT *
FROM v_stock_actual
WHERE stock_disponible <= stock_minimo;

CREATE VIEW v_kardex AS
SELECT
    mi.fecha_movimiento,
    mi.numero_movimiento,
    ins.codigo_interno,
    ins.nombre_insumo,
    mi.tipo_movimiento,
    CASE WHEN mi.tipo_movimiento IN ('ENTRADA_COMPRA', 'AJUSTE_POSITIVO', 'DEVOLUCION', 'TRANSFERENCIA_ENTRADA') THEN mi.cantidad ELSE 0 END AS entrada,
    CASE WHEN mi.tipo_movimiento IN ('SALIDA_DESPACHO', 'AJUSTE_NEGATIVO', 'TRANSFERENCIA_SALIDA') THEN mi.cantidad ELSE 0 END AS salida,
    mi.costo_unitario,
    mi.motivo,
    COALESCE(ao.nombre_almacen, '-') AS almacen_origen,
    COALESCE(ad.nombre_almacen, '-') AS almacen_destino,
    u.nombre_completo AS usuario_responsable,
    mi.documento_respaldo,
    mi.observaciones
FROM movimientos_inventario mi
INNER JOIN insumos ins ON ins.id_insumo = mi.id_insumo
LEFT JOIN almacenes ao ON ao.id_almacen = mi.id_almacen_origen
LEFT JOIN almacenes ad ON ad.id_almacen = mi.id_almacen_destino
LEFT JOIN usuarios u ON u.id_usuario = mi.usuario_responsable;

CREATE VIEW v_pedidos_por_estado AS
SELECT
    estado_pedido,
    COUNT(*) AS total_pedidos
FROM pedidos
GROUP BY estado_pedido;

CREATE VIEW v_compras_por_proveedor AS
SELECT
    p.codigo_proveedor,
    p.razon_social,
    COUNT(oc.id_orden_compra) AS total_compras,
    COALESCE(SUM(oc.total_final), 0) AS monto_total_comprado
FROM proveedores p
LEFT JOIN ordenes_compra oc ON oc.id_proveedor = p.id_proveedor
GROUP BY p.codigo_proveedor, p.razon_social;

CREATE VIEW v_dashboard_resumen AS
SELECT
    (SELECT COUNT(*) FROM insumos WHERE estado = 'ACTIVO') AS total_insumos_activos,
    (SELECT COUNT(*) FROM proveedores WHERE estado = 'ACTIVO') AS total_proveedores_activos,
    (SELECT COUNT(*) FROM almacenes WHERE estado = 'ACTIVO') AS total_almacenes_activos,
    (SELECT COUNT(*) FROM usuarios WHERE estado = 'ACTIVO') AS total_usuarios_activos,
    (SELECT COUNT(*) FROM pedidos WHERE estado_pedido = 'PENDIENTE') AS pedidos_pendientes,
    (SELECT COUNT(*) FROM pedidos WHERE estado_pedido = 'APROBADO') AS pedidos_aprobados,
    (SELECT COUNT(*) FROM ordenes_compra WHERE estado_compra IN ('PENDIENTE', 'EN_PROCESO')) AS compras_en_proceso,
    (SELECT COUNT(*) FROM ordenes_compra WHERE estado_compra = 'RECIBIDA_COMPLETA') AS compras_recibidas,
    (SELECT COUNT(*) FROM v_stock_bajo) AS insumos_con_stock_bajo,
    (SELECT COALESCE(SUM(valor_total_stock), 0) FROM inventarios) AS valor_total_inventario;

-- =============================================================================
-- =============================================================================
-- 12. DATOS MINIMOS DEL SISTEMA LIMPIO
-- =============================================================================
-- Objetivo:
-- - Mantener todas las tablas, relaciones, indices, funciones y vistas del sistema.
-- - Dejar vacias las tablas operativas: almacenes, proveedores, insumos,
--   inventario, pedidos, compras, despachos, notificaciones y auditorias.
-- - Crear solo la configuracion minima de acceso y el usuario administrador Federico.
--
-- Credenciales iniciales:
--   Usuario: federico
--   Password: fede2002
-- =============================================================================

BEGIN;

INSERT INTO areas (nombre_area, descripcion, estado)
VALUES
  ('Operaciones / Mina', 'Area responsable de la operacion minera.', 'ACTIVO'),
  ('Mantenimiento / Maestranza', 'Area encargada del mantenimiento de equipos e infraestructura.', 'ACTIVO'),
  ('Seguridad Industrial (HSE)', 'Area responsable de seguridad industrial y dotacion de EPP.', 'ACTIVO'),
  ('Logística / Almacenes', 'Area responsable del control fisico de insumos.', 'ACTIVO'),
  ('Administración / Gerencia', 'Area administrativa de apoyo.', 'ACTIVO'),
  ('Otros / Terceros', 'Area para terceros, otros servicios y casos no clasificados.', 'ACTIVO');

INSERT INTO roles (nombre_rol, descripcion, estado)
VALUES
  ('Administrador del sistema', 'Acceso total al sistema, usuarios, seguridad, reportes y auditoria.', 'ACTIVO'),
  ('Encargado de almacen', 'Responsable operativo de almacenes, inventario, movimientos y despachos.', 'ACTIVO'),
  ('Supervisor de mina', 'Solicita insumos para operacion minera y realiza seguimiento a pedidos.', 'ACTIVO'),
  ('Jefe de area', 'Responsable de revisar, aprobar, observar o rechazar pedidos del area.', 'ACTIVO'),
  ('Encargado de compras', 'Responsable de proveedores, compras, recepciones y comprobantes.', 'ACTIVO'),
  ('Auditor', 'Usuario con acceso de consulta a auditoria, trazabilidad y reportes.', 'ACTIVO'),
  ('Usuario solicitante', 'Usuario que crea pedidos de insumos y realiza seguimiento a sus solicitudes.', 'ACTIVO');

INSERT INTO permisos (codigo_permiso, modulo, descripcion)
VALUES
  ('dashboard.ver', 'Dashboard', 'Ver indicadores del dashboard.'),
  ('usuarios.ver', 'Usuarios', 'Ver usuarios.'),
  ('usuarios.crear', 'Usuarios', 'Crear usuarios.'),
  ('usuarios.editar', 'Usuarios', 'Editar usuarios.'),
  ('usuarios.eliminar', 'Usuarios', 'Eliminar usuarios.'),
  ('usuarios.activar', 'Usuarios', 'Activar usuarios.'),
  ('usuarios.desactivar', 'Usuarios', 'Desactivar usuarios.'),
  ('roles.ver', 'Usuarios', 'Ver roles y permisos.'),
  ('roles.editar', 'Usuarios', 'Editar roles.'),
  ('auditoria.ver', 'Auditoria', 'Ver auditoria.'),
  ('auditoria.detalle', 'Auditoria', 'Ver detalle de auditoria.'),
  ('catalogos.ver', 'Catalogos', 'Ver catalogos del sistema.'),
  ('almacenes.ver', 'Almacenes', 'Ver almacenes.'),
  ('almacenes.crear', 'Almacenes', 'Crear almacenes.'),
  ('almacenes.editar', 'Almacenes', 'Editar almacenes.'),
  ('almacenes.eliminar', 'Almacenes', 'Eliminar almacenes.'),
  ('almacenes.activar', 'Almacenes', 'Activar almacenes.'),
  ('almacenes.desactivar', 'Almacenes', 'Desactivar almacenes.'),
  ('proveedores.ver', 'Proveedores', 'Ver proveedores.'),
  ('proveedores.crear', 'Proveedores', 'Crear proveedores.'),
  ('proveedores.editar', 'Proveedores', 'Editar proveedores.'),
  ('proveedores.eliminar', 'Proveedores', 'Eliminar proveedores.'),
  ('proveedores.activar', 'Proveedores', 'Activar proveedores.'),
  ('proveedores.desactivar', 'Proveedores', 'Desactivar proveedores.'),
  ('insumos.ver', 'Insumos', 'Ver insumos.'),
  ('insumos.crear', 'Insumos', 'Crear insumos.'),
  ('insumos.editar', 'Insumos', 'Editar insumos.'),
  ('insumos.eliminar', 'Insumos', 'Eliminar insumos.'),
  ('insumos.activar', 'Insumos', 'Activar insumos.'),
  ('insumos.desactivar', 'Insumos', 'Desactivar insumos.'),
  ('inventario.ver', 'Inventario', 'Ver inventario.'),
  ('inventario.ajustar', 'Inventario', 'Registrar ajustes de inventario.'),
  ('inventario.transferir', 'Inventario', 'Registrar transferencias de inventario.'),
  ('inventario.devolver', 'Inventario', 'Registrar devoluciones de inventario.'),
  ('inventario.ver_movimientos', 'Inventario', 'Ver movimientos de inventario.'),
  ('inventario.ver_stock_critico', 'Inventario', 'Ver stock critico.'),
  ('despachos.ver', 'Despachos', 'Ver despachos.'),
  ('despachos.crear', 'Despachos', 'Crear despachos.'),
  ('despachos.detalle', 'Despachos', 'Ver detalle de despachos.'),
  ('pedidos.ver', 'Pedidos', 'Ver pedidos.'),
  ('pedidos.crear', 'Pedidos', 'Crear pedidos.'),
  ('pedidos.editar', 'Pedidos', 'Editar pedidos.'),
  ('pedidos.anular', 'Pedidos', 'Anular pedidos.'),
  ('pedidos.aprobar', 'Pedidos', 'Aprobar pedidos.'),
  ('pedidos.rechazar', 'Pedidos', 'Rechazar pedidos.'),
  ('pedidos.observar', 'Pedidos', 'Observar pedidos.'),
  ('pedidos.detalle', 'Pedidos', 'Ver detalle de pedidos.'),
  ('compras.ver', 'Compras', 'Ver compras.'),
  ('compras.crear_orden', 'Compras', 'Crear ordenes de compra.'),
  ('compras.editar_orden', 'Compras', 'Editar ordenes de compra.'),
  ('compras.detalle_orden', 'Compras', 'Ver detalle de ordenes de compra.'),
  ('recepciones.ver', 'Recepciones', 'Ver recepciones.'),
  ('recepciones.crear', 'Recepciones', 'Crear recepciones.'),
  ('recepciones.detalle', 'Recepciones', 'Ver detalle de recepciones.'),
  ('comprobantes.ver', 'Comprobantes', 'Ver comprobantes.'),
  ('comprobantes.crear', 'Comprobantes', 'Crear comprobantes.'),
  ('comprobantes.detalle', 'Comprobantes', 'Ver detalle de comprobantes.'),
  ('comprobantes.exportar_pdf', 'Comprobantes', 'Exportar comprobantes a PDF.'),
  ('reportes.ver', 'Reportes', 'Ver reportes.'),
  ('reportes.exportar', 'Reportes', 'Exportar reportes.'),
  ('reportes.imprimir', 'Reportes', 'Imprimir reportes.'),
  ('notificaciones.ver', 'Notificaciones', 'Ver notificaciones.'),
  ('notificaciones.marcar_leida', 'Notificaciones', 'Marcar notificaciones como leidas.'),
  ('notificaciones.eliminar', 'Notificaciones', 'Eliminar notificaciones.'),
  ('perfil.ver', 'Perfil', 'Ver perfil.'),
  ('perfil.editar', 'Perfil', 'Editar perfil.');

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM roles r
CROSS JOIN permisos p
WHERE r.nombre_rol = 'Administrador del sistema';

INSERT INTO usuarios (
  id_area,
  id_rol,
  nombre_completo,
  nombre_usuario,
  correo,
  cedula_identidad,
  complemento_ci,
  expedido_ci,
  password_hash,
  telefono,
  cargo,
  estado,
  intentos_fallidos,
  cambio_obligatorio
)
SELECT
  a.id_area,
  r.id_rol,
  'federico choquecallata villca',
  'federico',
  'feyckon@gmail.com',
  '12901305',
  NULL,
  'OR',
  '$2b$10$GgdiHI4w3VT.ZUWQZCyWx.1vCXIlRKPeL76SvnYgrSDKA12MncroC',
  '74477014',
  'presidente de Vigilancia',
  'ACTIVO',
  0,
  FALSE
FROM areas a
CROSS JOIN roles r
WHERE a.nombre_area = 'Administración / Gerencia'
  AND r.nombre_rol = 'Administrador del sistema';

COMMIT;

-- =============================================================================
-- VERIFICACION RAPIDA DESPUES DE IMPORTAR
-- =============================================================================
-- SELECT nombre_usuario, nombre_completo, estado FROM usuarios;
-- SELECT COUNT(*) AS almacenes FROM almacenes;
-- SELECT COUNT(*) AS proveedores FROM proveedores;
-- SELECT COUNT(*) AS insumos FROM insumos;
-- SELECT COUNT(*) AS pedidos FROM pedidos;
-- SELECT COUNT(*) AS ordenes_compra FROM ordenes_compra;
-- SELECT COUNT(*) AS inventarios FROM inventarios;
-- SELECT COUNT(*) AS despachos FROM despachos;
-- SELECT COUNT(*) AS notificaciones FROM notificaciones;
-- SELECT COUNT(*) AS auditorias FROM auditorias;
